"""Every Fulkruma feature route, one method each — generated by apigen from
backend/openapi.json. Do not edit by hand; regenerate after the API changes.

Reach them as ``client.api.<area>_<action>(...)``. Each call goes through the
client's own ``_apigen_request`` (its sign-in and response envelope).
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


class GeneratedApi:
    """All 79 feature routes of the Fulkruma API."""

    def __init__(self, client: Any) -> None:
        self._client = client

    def _call(self, method: str, path: str, query: Dict[str, Any], body: Optional[Dict[str, Any]]) -> Any:
        query = {k: v for k, v in query.items() if v is not None}
        return self._client._apigen_request(method, path, query=query or None, body=body)

    def addresses_create(self, *, customer_id: Optional[str] = None, label: Optional[str] = None, contact_name: Optional[str] = None, contact_phone: Optional[str] = None, email: Optional[str] = None, address: Optional[str] = None, note: Optional[str] = None, postal_code: Optional[str] = None, area_id: Optional[str] = None, lat: Optional[float] = None, lng: Optional[float] = None, is_default: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an address (POST /api/v1/addresses).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if customer_id is not None:
            payload["customerId"] = customer_id
        if label is not None:
            payload["label"] = label
        if contact_name is not None:
            payload["contactName"] = contact_name
        if contact_phone is not None:
            payload["contactPhone"] = contact_phone
        if email is not None:
            payload["email"] = email
        if address is not None:
            payload["address"] = address
        if note is not None:
            payload["note"] = note
        if postal_code is not None:
            payload["postalCode"] = postal_code
        if area_id is not None:
            payload["areaId"] = area_id
        if lat is not None:
            payload["lat"] = lat
        if lng is not None:
            payload["lng"] = lng
        if is_default is not None:
            payload["isDefault"] = is_default
        if "customerId" not in payload:
            raise ValueError("addresses_create needs customer_id")
        if "label" not in payload:
            raise ValueError("addresses_create needs label")
        if "contactName" not in payload:
            raise ValueError("addresses_create needs contact_name")
        if "contactPhone" not in payload:
            raise ValueError("addresses_create needs contact_phone")
        if "address" not in payload:
            raise ValueError("addresses_create needs address")
        return self._call("POST", f"/api/v1/addresses", {}, payload)

    def addresses_delete(self, id_: str) -> Any:
        """Delete an address (DELETE /api/v1/addresses/{id})."""
        return self._call("DELETE", f"/api/v1/addresses/{_q(id_)}", {}, None)

    def addresses_list(self, *, customer_id: Optional[Any] = None) -> Any:
        """List addresses (GET /api/v1/addresses)."""
        return self._call("GET", f"/api/v1/addresses", {"customer_id": customer_id}, None)

    def addresses_update(self, id_: str, *, label: Optional[str] = None, contact_name: Optional[str] = None, contact_phone: Optional[str] = None, email: Optional[str] = None, address: Optional[str] = None, note: Optional[str] = None, postal_code: Optional[str] = None, area_id: Optional[str] = None, lat: Optional[float] = None, lng: Optional[float] = None, is_default: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update an address (PATCH /api/v1/addresses/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if label is not None:
            payload["label"] = label
        if contact_name is not None:
            payload["contactName"] = contact_name
        if contact_phone is not None:
            payload["contactPhone"] = contact_phone
        if email is not None:
            payload["email"] = email
        if address is not None:
            payload["address"] = address
        if note is not None:
            payload["note"] = note
        if postal_code is not None:
            payload["postalCode"] = postal_code
        if area_id is not None:
            payload["areaId"] = area_id
        if lat is not None:
            payload["lat"] = lat
        if lng is not None:
            payload["lng"] = lng
        if is_default is not None:
            payload["isDefault"] = is_default
        return self._call("PATCH", f"/api/v1/addresses/{_q(id_)}", {}, payload)

    def api_keys_create(self, *, name: Optional[str] = None, scopes: Optional[List[Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an api key (POST /api/v1/api-keys).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if scopes is not None:
            payload["scopes"] = scopes
        if "name" not in payload:
            raise ValueError("api_keys_create needs name")
        return self._call("POST", f"/api/v1/api-keys", {}, payload)

    def api_keys_list(self) -> Any:
        """List api keys (GET /api/v1/api-keys)."""
        return self._call("GET", f"/api/v1/api-keys", {}, None)

    def api_keys_revoke(self, id_: str) -> Any:
        """Revoke an api key (POST /api/v1/api-keys/{id}/revoke)."""
        return self._call("POST", f"/api/v1/api-keys/{_q(id_)}/revoke", {}, None)

    def audit_log_list(self, *, action: Optional[Any] = None, limit: Optional[Any] = None, target_type: Optional[Any] = None) -> Any:
        """List audit log (GET /api/v1/audit-log)."""
        return self._call("GET", f"/api/v1/audit-log", {"action": action, "limit": limit, "target_type": target_type}, None)

    def billing_cancel(self, *, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a cancel (POST /api/v1/billing/cancel)."""
        payload: Dict[str, Any] = dict(json_body or {})
        return self._call("POST", f"/api/v1/billing/cancel", {}, payload)

    def billing_checkout(self, *, plan: Optional[str] = None, email: Optional[str] = None, name: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a checkout (POST /api/v1/billing/checkout).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        plan: one of STARTER, GROWTH, SCALE"""
        payload: Dict[str, Any] = dict(json_body or {})
        if plan is not None:
            payload["plan"] = plan
        if email is not None:
            payload["email"] = email
        if name is not None:
            payload["name"] = name
        if "plan" not in payload:
            raise ValueError("billing_checkout needs plan")
        return self._call("POST", f"/api/v1/billing/checkout", {}, payload)

    def billing_invoices(self, *, cursor: Optional[Any] = None, limit: Optional[Any] = None) -> Any:
        """List invoices (GET /api/v1/billing/invoices)."""
        return self._call("GET", f"/api/v1/billing/invoices", {"cursor": cursor, "limit": limit}, None)

    def billing_plan(self) -> Any:
        """List plan (GET /api/v1/billing/plan)."""
        return self._call("GET", f"/api/v1/billing/plan", {}, None)

    def billing_plans(self) -> Any:
        """Public, no auth. (GET /api/v1/billing/plans)."""
        return self._call("GET", f"/api/v1/billing/plans", {}, None)

    def billing_subscription(self) -> Any:
        """List subscription (GET /api/v1/billing/subscription)."""
        return self._call("GET", f"/api/v1/billing/subscription", {}, None)

    def billing_usage(self) -> Any:
        """List usage (GET /api/v1/billing/usage)."""
        return self._call("GET", f"/api/v1/billing/usage", {}, None)

    def deliveries_create(self, *, product_id: Optional[str] = None, customer_id: Optional[str] = None, checkout_session_id: Optional[str] = None, max_downloads: Optional[int] = None, expires_at: Optional[str] = None, external_source: Optional[str] = None, external_ref: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a delivery (POST /api/v1/deliveries).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if product_id is not None:
            payload["productId"] = product_id
        if customer_id is not None:
            payload["customerId"] = customer_id
        if checkout_session_id is not None:
            payload["checkoutSessionId"] = checkout_session_id
        if max_downloads is not None:
            payload["maxDownloads"] = max_downloads
        if expires_at is not None:
            payload["expiresAt"] = expires_at
        if external_source is not None:
            payload["externalSource"] = external_source
        if external_ref is not None:
            payload["externalRef"] = external_ref
        if "productId" not in payload:
            raise ValueError("deliveries_create needs product_id")
        if "customerId" not in payload:
            raise ValueError("deliveries_create needs customer_id")
        if "checkoutSessionId" not in payload:
            raise ValueError("deliveries_create needs checkout_session_id")
        return self._call("POST", f"/api/v1/deliveries", {}, payload)

    def deliveries_extend(self, id_: str) -> Any:
        """Extend the download window 30 days (from now, or the current expiry). (POST /api/v1/deliveries/{id}/extend)."""
        return self._call("POST", f"/api/v1/deliveries/{_q(id_)}/extend", {}, None)

    def deliveries_get(self, id_: str) -> Any:
        """Get a delivery (GET /api/v1/deliveries/{id})."""
        return self._call("GET", f"/api/v1/deliveries/{_q(id_)}", {}, None)

    def deliveries_list(self) -> Any:
        """List deliveries (GET /api/v1/deliveries)."""
        return self._call("GET", f"/api/v1/deliveries", {}, None)

    def deliveries_reset_downloads(self, id_: str) -> Any:
        """Reset the download counter so the buyer can download again. (POST /api/v1/deliveries/{id}/reset-downloads)."""
        return self._call("POST", f"/api/v1/deliveries/{_q(id_)}/reset-downloads", {}, None)

    def deliveries_revoke(self, id_: str) -> Any:
        """Revoke: expire the delivery now. (POST /api/v1/deliveries/{id}/revoke)."""
        return self._call("POST", f"/api/v1/deliveries/{_q(id_)}/revoke", {}, None)

    def integrations_status(self) -> Any:
        """List status (GET /api/v1/integrations/status)."""
        return self._call("GET", f"/api/v1/integrations/status", {}, None)

    def licenses_activate(self, *, key: Optional[str] = None, instance_id: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """/v1/licenses/activate is unauthenticated — buyers' apps call this with the license key directly. (POST /api/v1/licenses/activate).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if key is not None:
            payload["key"] = key
        if instance_id is not None:
            payload["instanceId"] = instance_id
        if "key" not in payload:
            raise ValueError("licenses_activate needs key")
        if "instanceId" not in payload:
            raise ValueError("licenses_activate needs instance_id")
        return self._call("POST", f"/api/v1/licenses/activate", {}, payload)

    def licenses_create(self, *, product_id: Optional[str] = None, customer_id: Optional[str] = None, max_activations: Optional[int] = None, expires_at: Optional[str] = None, external_source: Optional[str] = None, external_ref: Optional[str] = None, key: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a license (POST /api/v1/licenses).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if product_id is not None:
            payload["productId"] = product_id
        if customer_id is not None:
            payload["customerId"] = customer_id
        if max_activations is not None:
            payload["maxActivations"] = max_activations
        if expires_at is not None:
            payload["expiresAt"] = expires_at
        if external_source is not None:
            payload["externalSource"] = external_source
        if external_ref is not None:
            payload["externalRef"] = external_ref
        if key is not None:
            payload["key"] = key
        if "productId" not in payload:
            raise ValueError("licenses_create needs product_id")
        if "customerId" not in payload:
            raise ValueError("licenses_create needs customer_id")
        return self._call("POST", f"/api/v1/licenses", {}, payload)

    def licenses_deactivate(self, *, key: Optional[str] = None, instance_id: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Release a previously-activated instance. (POST /api/v1/licenses/deactivate).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if key is not None:
            payload["key"] = key
        if instance_id is not None:
            payload["instanceId"] = instance_id
        if "key" not in payload:
            raise ValueError("licenses_deactivate needs key")
        if "instanceId" not in payload:
            raise ValueError("licenses_deactivate needs instance_id")
        return self._call("POST", f"/api/v1/licenses/deactivate", {}, payload)

    def licenses_list(self) -> Any:
        """List licenses (GET /api/v1/licenses)."""
        return self._call("GET", f"/api/v1/licenses", {}, None)

    def licenses_lookup(self, *, key: str) -> Any:
        """Full license + its activation rows, resolved by key within the merchant's account. (GET /api/v1/licenses/lookup)."""
        return self._call("GET", f"/api/v1/licenses/lookup", {"key": key}, None)

    def licenses_revoke(self, id_: str) -> Any:
        """Revoke a license (POST /api/v1/licenses/{id}/revoke)."""
        return self._call("POST", f"/api/v1/licenses/{_q(id_)}/revoke", {}, None)

    def licenses_validate(self, *, key: str, product_id: Optional[str] = None) -> Any:
        """Public unauthenticated endpoints — buyers' software calls these with just the license key. (GET /api/v1/licenses/validate)."""
        return self._call("GET", f"/api/v1/licenses/validate", {"key": key, "productId": product_id}, None)

    def products_create(self, *, name: Optional[str] = None, sku: Optional[str] = None, description: Optional[str] = None, type_: Optional[str] = None, weight: Optional[int] = None, length: Optional[int] = None, width: Optional[int] = None, height: Optional[int] = None, license_enabled: Optional[bool] = None, max_activations: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a product (POST /api/v1/products).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        type_: one of physical, digital, license"""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if sku is not None:
            payload["sku"] = sku
        if description is not None:
            payload["description"] = description
        if type_ is not None:
            payload["type"] = type_
        if weight is not None:
            payload["weight"] = weight
        if length is not None:
            payload["length"] = length
        if width is not None:
            payload["width"] = width
        if height is not None:
            payload["height"] = height
        if license_enabled is not None:
            payload["licenseEnabled"] = license_enabled
        if max_activations is not None:
            payload["maxActivations"] = max_activations
        if "name" not in payload:
            raise ValueError("products_create needs name")
        return self._call("POST", f"/api/v1/products", {}, payload)

    def products_create_variants(self, id_: str, *, sku: Optional[str] = None, name: Optional[str] = None, price_cents: Optional[int] = None, cost_cents: Optional[int] = None, low_stock_threshold: Optional[int] = None, weight: Optional[int] = None, is_default: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Variants a product (POST /api/v1/products/{id}/variants).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if sku is not None:
            payload["sku"] = sku
        if name is not None:
            payload["name"] = name
        if price_cents is not None:
            payload["priceCents"] = price_cents
        if cost_cents is not None:
            payload["costCents"] = cost_cents
        if low_stock_threshold is not None:
            payload["lowStockThreshold"] = low_stock_threshold
        if weight is not None:
            payload["weight"] = weight
        if is_default is not None:
            payload["isDefault"] = is_default
        if "name" not in payload:
            raise ValueError("products_create_variants needs name")
        return self._call("POST", f"/api/v1/products/{_q(id_)}/variants", {}, payload)

    def products_delete(self, id_: str) -> Any:
        """Delete a product (DELETE /api/v1/products/{id})."""
        return self._call("DELETE", f"/api/v1/products/{_q(id_)}", {}, None)

    def products_delete_variants(self, id_: str, variant_id: str) -> Any:
        """Delete a variant (DELETE /api/v1/products/{id}/variants/{variantId})."""
        return self._call("DELETE", f"/api/v1/products/{_q(id_)}/variants/{_q(variant_id)}", {}, None)

    def products_get(self, id_: str) -> Any:
        """Get a product (GET /api/v1/products/{id})."""
        return self._call("GET", f"/api/v1/products/{_q(id_)}", {}, None)

    def products_list(self, *, archived: Optional[Any] = None) -> Any:
        """List products (GET /api/v1/products)."""
        return self._call("GET", f"/api/v1/products", {"archived": archived}, None)

    def products_update(self, id_: str, *, name: Optional[str] = None, sku: Optional[str] = None, description: Optional[str] = None, type_: Optional[str] = None, weight: Optional[int] = None, length: Optional[int] = None, width: Optional[int] = None, height: Optional[int] = None, license_enabled: Optional[bool] = None, max_activations: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a product (PATCH /api/v1/products/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        type_: one of physical, digital, license"""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if sku is not None:
            payload["sku"] = sku
        if description is not None:
            payload["description"] = description
        if type_ is not None:
            payload["type"] = type_
        if weight is not None:
            payload["weight"] = weight
        if length is not None:
            payload["length"] = length
        if width is not None:
            payload["width"] = width
        if height is not None:
            payload["height"] = height
        if license_enabled is not None:
            payload["licenseEnabled"] = license_enabled
        if max_activations is not None:
            payload["maxActivations"] = max_activations
        return self._call("PATCH", f"/api/v1/products/{_q(id_)}", {}, payload)

    def products_update_variants(self, id_: str, variant_id: str, *, sku: Optional[str] = None, name: Optional[str] = None, price_cents: Optional[int] = None, cost_cents: Optional[int] = None, low_stock_threshold: Optional[int] = None, weight: Optional[int] = None, is_default: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a variant (PATCH /api/v1/products/{id}/variants/{variantId}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if sku is not None:
            payload["sku"] = sku
        if name is not None:
            payload["name"] = name
        if price_cents is not None:
            payload["priceCents"] = price_cents
        if cost_cents is not None:
            payload["costCents"] = cost_cents
        if low_stock_threshold is not None:
            payload["lowStockThreshold"] = low_stock_threshold
        if weight is not None:
            payload["weight"] = weight
        if is_default is not None:
            payload["isDefault"] = is_default
        return self._call("PATCH", f"/api/v1/products/{_q(id_)}/variants/{_q(variant_id)}", {}, payload)

    def shipments_cancel(self, id_: str, *, reason: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Cancel a booking the courier hasn't collected yet, and give back the shipping credit confirm-pickup consumed. (POST /api/v1/shipments/{id}/cancel).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if reason is not None:
            payload["reason"] = reason
        return self._call("POST", f"/api/v1/shipments/{_q(id_)}/cancel", {}, payload)

    def shipments_confirm_pickup(self, id_: str) -> Any:
        """F-004: Merchant clicks "Book courier" once the parcel is actually ready. (POST /api/v1/shipments/{id}/confirm-pickup)."""
        return self._call("POST", f"/api/v1/shipments/{_q(id_)}/confirm-pickup", {}, None)

    def shipments_create(self, *, product_id: Optional[str] = None, checkout_session_id: Optional[str] = None, customer_id: Optional[str] = None, customer_email: Optional[str] = None, courier_code: Optional[str] = None, courier_service_code: Optional[str] = None, courier_type: Optional[str] = None, price: Optional[int] = None, insurance: Optional[int] = None, insured: Optional[bool] = None, origin: Optional[Dict[str, Any]] = None, destination: Optional[Dict[str, Any]] = None, items: Optional[List[Any]] = None, external_source: Optional[str] = None, external_ref: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a shipment (POST /api/v1/shipments).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if product_id is not None:
            payload["productId"] = product_id
        if checkout_session_id is not None:
            payload["checkoutSessionId"] = checkout_session_id
        if customer_id is not None:
            payload["customerId"] = customer_id
        if customer_email is not None:
            payload["customerEmail"] = customer_email
        if courier_code is not None:
            payload["courierCode"] = courier_code
        if courier_service_code is not None:
            payload["courierServiceCode"] = courier_service_code
        if courier_type is not None:
            payload["courierType"] = courier_type
        if price is not None:
            payload["price"] = price
        if insurance is not None:
            payload["insurance"] = insurance
        if insured is not None:
            payload["insured"] = insured
        if origin is not None:
            payload["origin"] = origin
        if destination is not None:
            payload["destination"] = destination
        if items is not None:
            payload["items"] = items
        if external_source is not None:
            payload["externalSource"] = external_source
        if external_ref is not None:
            payload["externalRef"] = external_ref
        if "courierCode" not in payload:
            raise ValueError("shipments_create needs courier_code")
        if "courierServiceCode" not in payload:
            raise ValueError("shipments_create needs courier_service_code")
        if "courierType" not in payload:
            raise ValueError("shipments_create needs courier_type")
        if "price" not in payload:
            raise ValueError("shipments_create needs price")
        if "origin" not in payload:
            raise ValueError("shipments_create needs origin")
        if "destination" not in payload:
            raise ValueError("shipments_create needs destination")
        if "items" not in payload:
            raise ValueError("shipments_create needs items")
        return self._call("POST", f"/api/v1/shipments", {}, payload)

    def shipments_get(self, id_: str) -> Any:
        """Get a shipment (GET /api/v1/shipments/{id})."""
        return self._call("GET", f"/api/v1/shipments/{_q(id_)}", {}, None)

    def shipments_label(self, id_: str, *, size: Optional[str] = None, show_sender_phone: Optional[str] = None, show_recipient_phone: Optional[str] = None, mask_recipient_name: Optional[str] = None, mask_recipient_phone: Optional[str] = None, show_shipping_cost: Optional[str] = None, show_insurance: Optional[str] = None, show_items: Optional[str] = None, show_item_descriptions: Optional[str] = None, show_item_skus: Optional[str] = None) -> Any:
        """Biteship deliberately has no shipping-label API. (GET /api/v1/shipments/{id}/label)."""
        return self._call("GET", f"/api/v1/shipments/{_q(id_)}/label", {"size": size, "showSenderPhone": show_sender_phone, "showRecipientPhone": show_recipient_phone, "maskRecipientName": mask_recipient_name, "maskRecipientPhone": mask_recipient_phone, "showShippingCost": show_shipping_cost, "showInsurance": show_insurance, "showItems": show_items, "showItemDescriptions": show_item_descriptions, "showItemSkus": show_item_skus}, None)

    def shipments_list(self, *, status: Optional[Any] = None) -> Any:
        """List shipments (GET /api/v1/shipments)."""
        return self._call("GET", f"/api/v1/shipments", {"status": status}, None)

    def shipments_rebook(self, id_: str, *, courier_code: Optional[str] = None, courier_service_code: Optional[str] = None, courier_type: Optional[str] = None, price: Optional[int] = None, insured: Optional[bool] = None, insurance: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Rebook a shipment (POST /api/v1/shipments/{id}/rebook).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if courier_code is not None:
            payload["courierCode"] = courier_code
        if courier_service_code is not None:
            payload["courierServiceCode"] = courier_service_code
        if courier_type is not None:
            payload["courierType"] = courier_type
        if price is not None:
            payload["price"] = price
        if insured is not None:
            payload["insured"] = insured
        if insurance is not None:
            payload["insurance"] = insurance
        return self._call("POST", f"/api/v1/shipments/{_q(id_)}/rebook", {}, payload)

    def shipments_tracking(self, id_: str) -> Any:
        """F-008: live tracking detail (driver, status history, ETA) from Biteship. (GET /api/v1/shipments/{id}/tracking)."""
        return self._call("GET", f"/api/v1/shipments/{_q(id_)}/tracking", {}, None)

    def shipping_areas(self, *, q: Optional[Any] = None) -> Any:
        """List areas (GET /api/v1/shipping/areas)."""
        return self._call("GET", f"/api/v1/shipping/areas", {"q": q}, None)

    def shipping_config(self) -> Any:
        """List config (GET /api/v1/shipping/config)."""
        return self._call("GET", f"/api/v1/shipping/config", {}, None)

    def shipping_couriers(self) -> Any:
        """In Fulkruma we still gate this behind requireAuth: the dashboard always has a session, and we want per-merchant API key resolution. (GET /api/v1/shipping/couriers)."""
        return self._call("GET", f"/api/v1/shipping/couriers", {}, None)

    def shipping_origin(self) -> Any:
        """List origin (GET /api/v1/shipping/origin)."""
        return self._call("GET", f"/api/v1/shipping/origin", {}, None)

    def shipping_rates(self, *, destination: Optional[Dict[str, Any]] = None, items: Optional[List[Any]] = None, insurance: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a rate (POST /api/v1/shipping/rates).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if destination is not None:
            payload["destination"] = destination
        if items is not None:
            payload["items"] = items
        if insurance is not None:
            payload["insurance"] = insurance
        if "destination" not in payload:
            raise ValueError("shipping_rates needs destination")
        if "items" not in payload:
            raise ValueError("shipping_rates needs items")
        return self._call("POST", f"/api/v1/shipping/rates", {}, payload)

    def shipping_set_config(self, *, api_key: Optional[str] = None, default_origin_id: Optional[str] = None, enabled_couriers: Optional[List[Any]] = None, default_courier: Optional[str] = None, active: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Set config (PUT /api/v1/shipping/config).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if api_key is not None:
            payload["apiKey"] = api_key
        if default_origin_id is not None:
            payload["defaultOriginId"] = default_origin_id
        if enabled_couriers is not None:
            payload["enabledCouriers"] = enabled_couriers
        if default_courier is not None:
            payload["defaultCourier"] = default_courier
        if active is not None:
            payload["active"] = active
        return self._call("PUT", f"/api/v1/shipping/config", {}, payload)

    def shipping_shipments(self, *, cursor: Optional[Any] = None, limit: Optional[Any] = None, status: Optional[Any] = None) -> Any:
        """List shipments (GET /api/v1/shipping/shipments)."""
        return self._call("GET", f"/api/v1/shipping/shipments", {"cursor": cursor, "limit": limit, "status": status}, None)

    def shipping_shipments_2(self, id_: str) -> Any:
        """Get a shipment (GET /api/v1/shipping/shipments/{id})."""
        return self._call("GET", f"/api/v1/shipping/shipments/{_q(id_)}", {}, None)

    def shipping_shipments_cancel(self, id_: str, *, reason: Optional[Any] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Legacy namespace. (POST /api/v1/shipping/shipments/{id}/cancel).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if reason is not None:
            payload["reason"] = reason
        return self._call("POST", f"/api/v1/shipping/shipments/{_q(id_)}/cancel", {}, payload)

    def shipping_shipments_label(self, id_: str, *, size: Optional[Any] = None) -> Any:
        """Legacy shipping namespace. (GET /api/v1/shipping/shipments/{id}/label)."""
        return self._call("GET", f"/api/v1/shipping/shipments/{_q(id_)}/label", {"size": size}, None)

    def shipping_shipments_rebook(self, id_: str, *, courier_code: Optional[str] = None, courier_service_code: Optional[str] = None, courier_type: Optional[str] = None, price: Optional[int] = None, insured: Optional[bool] = None, insurance: Optional[int] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Legacy-namespace twin of /shipments/:id/rebook. (POST /api/v1/shipping/shipments/{id}/rebook).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if courier_code is not None:
            payload["courierCode"] = courier_code
        if courier_service_code is not None:
            payload["courierServiceCode"] = courier_service_code
        if courier_type is not None:
            payload["courierType"] = courier_type
        if price is not None:
            payload["price"] = price
        if insured is not None:
            payload["insured"] = insured
        if insurance is not None:
            payload["insurance"] = insurance
        return self._call("POST", f"/api/v1/shipping/shipments/{_q(id_)}/rebook", {}, payload)

    def shipping_track(self, waybill_id: str, *, courier: Optional[Any] = None) -> Any:
        """Get a track (GET /api/v1/shipping/track/{waybillId})."""
        return self._call("GET", f"/api/v1/shipping/track/{_q(waybill_id)}", {"courier": courier}, None)

    def shipping_update_origin(self, *, address: Optional[str] = None, province: Optional[str] = None, city: Optional[str] = None, district: Optional[str] = None, village: Optional[str] = None, postal: Optional[str] = None, area_id: Optional[str] = None, lat: Optional[float] = None, lng: Optional[float] = None, note: Optional[str] = None, contact_name: Optional[str] = None, contact_phone: Optional[str] = None, couriers: Optional[List[Any]] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update origin (PATCH /api/v1/shipping/origin).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if address is not None:
            payload["address"] = address
        if province is not None:
            payload["province"] = province
        if city is not None:
            payload["city"] = city
        if district is not None:
            payload["district"] = district
        if village is not None:
            payload["village"] = village
        if postal is not None:
            payload["postal"] = postal
        if area_id is not None:
            payload["areaId"] = area_id
        if lat is not None:
            payload["lat"] = lat
        if lng is not None:
            payload["lng"] = lng
        if note is not None:
            payload["note"] = note
        if contact_name is not None:
            payload["contactName"] = contact_name
        if contact_phone is not None:
            payload["contactPhone"] = contact_phone
        if couriers is not None:
            payload["couriers"] = couriers
        if "address" not in payload:
            raise ValueError("shipping_update_origin needs address")
        if "contactName" not in payload:
            raise ValueError("shipping_update_origin needs contact_name")
        if "contactPhone" not in payload:
            raise ValueError("shipping_update_origin needs contact_phone")
        return self._call("PATCH", f"/api/v1/shipping/origin", {}, payload)

    def shipping_credits_adjust(self, *, amount: Optional[int] = None, kind: Optional[str] = None, shipment_id: Optional[str] = None, external_ref: Optional[str] = None, memo: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an adjust (POST /api/v1/shipping-credits/adjust).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        kind: one of manual_adjustment, shipment_refund"""
        payload: Dict[str, Any] = dict(json_body or {})
        if amount is not None:
            payload["amount"] = amount
        if kind is not None:
            payload["kind"] = kind
        if shipment_id is not None:
            payload["shipmentId"] = shipment_id
        if external_ref is not None:
            payload["externalRef"] = external_ref
        if memo is not None:
            payload["memo"] = memo
        if "amount" not in payload:
            raise ValueError("shipping_credits_adjust needs amount")
        if "kind" not in payload:
            raise ValueError("shipping_credits_adjust needs kind")
        return self._call("POST", f"/api/v1/shipping-credits/adjust", {}, payload)

    def shipping_credits_checkout(self, *, amount: Optional[int] = None, email: Optional[str] = None, name: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a checkout (POST /api/v1/shipping-credits/checkout).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if amount is not None:
            payload["amount"] = amount
        if email is not None:
            payload["email"] = email
        if name is not None:
            payload["name"] = name
        if "amount" not in payload:
            raise ValueError("shipping_credits_checkout needs amount")
        return self._call("POST", f"/api/v1/shipping-credits/checkout", {}, payload)

    def shipping_credits_list(self) -> Any:
        """Balance for the calling merchant. (GET /api/v1/shipping-credits)."""
        return self._call("GET", f"/api/v1/shipping-credits", {}, None)

    def shipping_credits_topup(self, *, amount: Optional[int] = None, external_ref: Optional[str] = None, memo: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a topup (POST /api/v1/shipping-credits/topup).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if amount is not None:
            payload["amount"] = amount
        if external_ref is not None:
            payload["externalRef"] = external_ref
        if memo is not None:
            payload["memo"] = memo
        if "amount" not in payload:
            raise ValueError("shipping_credits_topup needs amount")
        return self._call("POST", f"/api/v1/shipping-credits/topup", {}, payload)

    def shipping_credits_transactions(self, *, limit: Optional[int] = None, cursor: Optional[str] = None) -> Any:
        """List transactions (GET /api/v1/shipping-credits/transactions)."""
        return self._call("GET", f"/api/v1/shipping-credits/transactions", {"limit": limit, "cursor": cursor}, None)

    def stats_overview(self) -> Any:
        """Powers the /dashboard overview tiles. (GET /api/v1/stats/overview)."""
        return self._call("GET", f"/api/v1/stats/overview", {}, None)

    def stock_adjust(self, *, variant_id: Optional[str] = None, warehouse_id: Optional[str] = None, delta: Optional[int] = None, reason: Optional[str] = None, note: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create an adjust (POST /api/v1/stock/adjust).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it).
        reason: one of manual_adjust, initial_stock, transfer_in, transfer_out, damaged, returned_to_supplier, refund_restock, import"""
        payload: Dict[str, Any] = dict(json_body or {})
        if variant_id is not None:
            payload["variantId"] = variant_id
        if warehouse_id is not None:
            payload["warehouseId"] = warehouse_id
        if delta is not None:
            payload["delta"] = delta
        if reason is not None:
            payload["reason"] = reason
        if note is not None:
            payload["note"] = note
        if "variantId" not in payload:
            raise ValueError("stock_adjust needs variant_id")
        if "warehouseId" not in payload:
            raise ValueError("stock_adjust needs warehouse_id")
        if "delta" not in payload:
            raise ValueError("stock_adjust needs delta")
        if "reason" not in payload:
            raise ValueError("stock_adjust needs reason")
        return self._call("POST", f"/api/v1/stock/adjust", {}, payload)

    def stock_levels(self, *, variant_id: Optional[Any] = None) -> Any:
        """List levels (GET /api/v1/stock/levels)."""
        return self._call("GET", f"/api/v1/stock/levels", {"variant_id": variant_id}, None)

    def stock_movements(self, *, variant_id: Optional[Any] = None) -> Any:
        """List movements (GET /api/v1/stock/movements)."""
        return self._call("GET", f"/api/v1/stock/movements", {"variant_id": variant_id}, None)

    def stock_reservations(self) -> Any:
        """List reservations (GET /api/v1/stock/reservations)."""
        return self._call("GET", f"/api/v1/stock/reservations", {}, None)

    def warehouses_create(self, *, name: Optional[str] = None, address: Optional[str] = None, city: Optional[str] = None, postal: Optional[str] = None, lat: Optional[float] = None, lng: Optional[float] = None, phone: Optional[str] = None, is_default: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Create a warehouse (POST /api/v1/warehouses).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if address is not None:
            payload["address"] = address
        if city is not None:
            payload["city"] = city
        if postal is not None:
            payload["postal"] = postal
        if lat is not None:
            payload["lat"] = lat
        if lng is not None:
            payload["lng"] = lng
        if phone is not None:
            payload["phone"] = phone
        if is_default is not None:
            payload["isDefault"] = is_default
        if "name" not in payload:
            raise ValueError("warehouses_create needs name")
        return self._call("POST", f"/api/v1/warehouses", {}, payload)

    def warehouses_delete(self, id_: str) -> Any:
        """Delete a warehouse (DELETE /api/v1/warehouses/{id})."""
        return self._call("DELETE", f"/api/v1/warehouses/{_q(id_)}", {}, None)

    def warehouses_list(self) -> Any:
        """List warehouses (GET /api/v1/warehouses)."""
        return self._call("GET", f"/api/v1/warehouses", {}, None)

    def warehouses_update(self, id_: str, *, name: Optional[str] = None, address: Optional[str] = None, city: Optional[str] = None, postal: Optional[str] = None, lat: Optional[float] = None, lng: Optional[float] = None, phone: Optional[str] = None, is_default: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update a warehouse (PATCH /api/v1/warehouses/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if name is not None:
            payload["name"] = name
        if address is not None:
            payload["address"] = address
        if city is not None:
            payload["city"] = city
        if postal is not None:
            payload["postal"] = postal
        if lat is not None:
            payload["lat"] = lat
        if lng is not None:
            payload["lng"] = lng
        if phone is not None:
            payload["phone"] = phone
        if is_default is not None:
            payload["isDefault"] = is_default
        return self._call("PATCH", f"/api/v1/warehouses/{_q(id_)}", {}, payload)

    def webhooks_create_endpoints(self, *, url: Optional[str] = None, events: Optional[List[Any]] = None, description: Optional[str] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Register an endpoint. (POST /api/v1/webhooks/endpoints).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if url is not None:
            payload["url"] = url
        if events is not None:
            payload["events"] = events
        if description is not None:
            payload["description"] = description
        if "url" not in payload:
            raise ValueError("webhooks_create_endpoints needs url")
        return self._call("POST", f"/api/v1/webhooks/endpoints", {}, payload)

    def webhooks_delete_endpoints(self, id_: str) -> Any:
        """Delete an endpoint (DELETE /api/v1/webhooks/endpoints/{id})."""
        return self._call("DELETE", f"/api/v1/webhooks/endpoints/{_q(id_)}", {}, None)

    def webhooks_endpoints(self) -> Any:
        """List endpoints (GET /api/v1/webhooks/endpoints)."""
        return self._call("GET", f"/api/v1/webhooks/endpoints", {}, None)

    def webhooks_events(self, *, limit: Optional[int] = None, cursor: Optional[str] = None, type_: Optional[str] = None, status: Optional[str] = None, endpoint_id: Optional[str] = None) -> Any:
        """List webhook deliveries. (GET /api/v1/webhooks/events)."""
        return self._call("GET", f"/api/v1/webhooks/events", {"limit": limit, "cursor": cursor, "type": type_, "status": status, "endpointId": endpoint_id}, None)

    def webhooks_events_2(self, id_: str) -> Any:
        """Get a webhook delivery. (GET /api/v1/webhooks/events/{id})."""
        return self._call("GET", f"/api/v1/webhooks/events/{_q(id_)}", {}, None)

    def webhooks_events_retry(self, id_: str) -> Any:
        """Retry a webhook delivery. (POST /api/v1/webhooks/events/{id}/retry)."""
        return self._call("POST", f"/api/v1/webhooks/events/{_q(id_)}/retry", {}, None)

    def webhooks_update_endpoints(self, id_: str, *, url: Optional[str] = None, events: Optional[List[Any]] = None, description: Optional[str] = None, active: Optional[bool] = None, json_body: Optional[Dict[str, Any]] = None) -> Any:
        """Update an endpoint. (PATCH /api/v1/webhooks/endpoints/{id}).
        
        Body fields are keyword arguments; `json_body=` passes the whole body (fields override it)."""
        payload: Dict[str, Any] = dict(json_body or {})
        if url is not None:
            payload["url"] = url
        if events is not None:
            payload["events"] = events
        if description is not None:
            payload["description"] = description
        if active is not None:
            payload["active"] = active
        return self._call("PATCH", f"/api/v1/webhooks/endpoints/{_q(id_)}", {}, payload)


def _q(value: Any) -> str:
    from urllib.parse import quote

    return quote(str(value), safe="")
