// Code generated by apigen from backend/openapi.json. DO NOT EDIT.

package fulkruma

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
)

// apigenTransport is the call behind every GeneratedAPI method: the SDK client sends it
// with its own sign-in and unwraps its own response envelope (a few hand-written lines
// in the client, apigenRequest). query is nil or the query string; body is nil (no body)
// or the JSON body. It returns the envelope's data, as JSON.
type apigenTransport interface {
	apigenRequest(ctx context.Context, method, path string, query url.Values, body map[string]any) (json.RawMessage, error)
}

// GeneratedAPI has all 79 feature routes of the Fulkruma API, one method each
// (generated from the API spec). A method takes the path parameters, then an *<Method>Args
// with the query fields (tagged query) and the JSON body fields (tagged json): required
// fields are plain values, optional ones pointers, slices or maps that nil leaves out,
// and Body passes the whole body. Each returns the response's data as JSON.
type GeneratedAPI struct{ c apigenTransport }

// Ptr returns a pointer to v, for the optional fields of the *Args structs.
func Ptr[T any](v T) *T { return &v }

// AddressesCreateArgs are the inputs of GeneratedAPI.AddressesCreate.
type AddressesCreateArgs struct {
	// CustomerID is "customerId" in the body, required.
	CustomerID string `json:"customerId"`

	// Label is "label" in the body, required.
	Label string `json:"label"`

	// ContactName is "contactName" in the body, required.
	ContactName string `json:"contactName"`

	// ContactPhone is "contactPhone" in the body, required.
	ContactPhone string `json:"contactPhone"`

	// Email is "email" in the body.
	Email *string `json:"email,omitempty"`

	// Address is "address" in the body, required.
	Address string `json:"address"`

	// Note is "note" in the body.
	Note *string `json:"note,omitempty"`

	// PostalCode is "postalCode" in the body.
	PostalCode *string `json:"postalCode,omitempty"`

	// AreaID is "areaId" in the body.
	AreaID *string `json:"areaId,omitempty"`

	// Lat is "lat" in the body.
	Lat *float64 `json:"lat,omitempty"`

	// Lng is "lng" in the body.
	Lng *float64 `json:"lng,omitempty"`

	// IsDefault is "isDefault" in the body.
	IsDefault *bool `json:"isDefault,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AddressesCreate calls POST /api/v1/addresses: Create an address.
func (a *GeneratedAPI) AddressesCreate(ctx context.Context, p *AddressesCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AddressesCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.CustomerID != "" {
		payload["customerId"] = p.CustomerID
	}
	if p.Label != "" {
		payload["label"] = p.Label
	}
	if p.ContactName != "" {
		payload["contactName"] = p.ContactName
	}
	if p.ContactPhone != "" {
		payload["contactPhone"] = p.ContactPhone
	}
	if p.Email != nil {
		payload["email"] = *p.Email
	}
	if p.Address != "" {
		payload["address"] = p.Address
	}
	if p.Note != nil {
		payload["note"] = *p.Note
	}
	if p.PostalCode != nil {
		payload["postalCode"] = *p.PostalCode
	}
	if p.AreaID != nil {
		payload["areaId"] = *p.AreaID
	}
	if p.Lat != nil {
		payload["lat"] = *p.Lat
	}
	if p.Lng != nil {
		payload["lng"] = *p.Lng
	}
	if p.IsDefault != nil {
		payload["isDefault"] = *p.IsDefault
	}
	if _, ok := payload["customerId"]; !ok {
		return nil, apigenMissing("AddressesCreate", "CustomerID")
	}
	if _, ok := payload["label"]; !ok {
		return nil, apigenMissing("AddressesCreate", "Label")
	}
	if _, ok := payload["contactName"]; !ok {
		return nil, apigenMissing("AddressesCreate", "ContactName")
	}
	if _, ok := payload["contactPhone"]; !ok {
		return nil, apigenMissing("AddressesCreate", "ContactPhone")
	}
	if _, ok := payload["address"]; !ok {
		return nil, apigenMissing("AddressesCreate", "Address")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/addresses", nil, payload)
}

// AddressesDelete calls DELETE /api/v1/addresses/{id}: Delete an address.
func (a *GeneratedAPI) AddressesDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/addresses/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// AddressesListArgs are the inputs of GeneratedAPI.AddressesList.
type AddressesListArgs struct {
	// CustomerID is "customer_id" in the query.
	CustomerID any `query:"customer_id"`
}

// AddressesList calls GET /api/v1/addresses: List addresses.
func (a *GeneratedAPI) AddressesList(ctx context.Context, p *AddressesListArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AddressesListArgs{}
	}
	q := url.Values{}
	if p.CustomerID != nil {
		q.Set("customer_id", apigenQueryValue(p.CustomerID))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/addresses", q, nil)
}

// AddressesUpdateArgs are the inputs of GeneratedAPI.AddressesUpdate.
type AddressesUpdateArgs struct {
	// Label is "label" in the body.
	Label *string `json:"label,omitempty"`

	// ContactName is "contactName" in the body.
	ContactName *string `json:"contactName,omitempty"`

	// ContactPhone is "contactPhone" in the body.
	ContactPhone *string `json:"contactPhone,omitempty"`

	// Email is "email" in the body.
	Email *string `json:"email,omitempty"`

	// Address is "address" in the body.
	Address *string `json:"address,omitempty"`

	// Note is "note" in the body.
	Note *string `json:"note,omitempty"`

	// PostalCode is "postalCode" in the body.
	PostalCode *string `json:"postalCode,omitempty"`

	// AreaID is "areaId" in the body.
	AreaID *string `json:"areaId,omitempty"`

	// Lat is "lat" in the body.
	Lat *float64 `json:"lat,omitempty"`

	// Lng is "lng" in the body.
	Lng *float64 `json:"lng,omitempty"`

	// IsDefault is "isDefault" in the body.
	IsDefault *bool `json:"isDefault,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AddressesUpdate calls PATCH /api/v1/addresses/{id}: Update an address.
func (a *GeneratedAPI) AddressesUpdate(ctx context.Context, id string, p *AddressesUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AddressesUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Label != nil {
		payload["label"] = *p.Label
	}
	if p.ContactName != nil {
		payload["contactName"] = *p.ContactName
	}
	if p.ContactPhone != nil {
		payload["contactPhone"] = *p.ContactPhone
	}
	if p.Email != nil {
		payload["email"] = *p.Email
	}
	if p.Address != nil {
		payload["address"] = *p.Address
	}
	if p.Note != nil {
		payload["note"] = *p.Note
	}
	if p.PostalCode != nil {
		payload["postalCode"] = *p.PostalCode
	}
	if p.AreaID != nil {
		payload["areaId"] = *p.AreaID
	}
	if p.Lat != nil {
		payload["lat"] = *p.Lat
	}
	if p.Lng != nil {
		payload["lng"] = *p.Lng
	}
	if p.IsDefault != nil {
		payload["isDefault"] = *p.IsDefault
	}
	path := "/api/v1/addresses/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// APIKeysCreateArgs are the inputs of GeneratedAPI.APIKeysCreate.
type APIKeysCreateArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Scopes is "scopes" in the body.
	Scopes []string `json:"scopes,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// APIKeysCreate calls POST /api/v1/api-keys: Create an api key.
func (a *GeneratedAPI) APIKeysCreate(ctx context.Context, p *APIKeysCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &APIKeysCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.Scopes != nil {
		payload["scopes"] = p.Scopes
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("APIKeysCreate", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/api-keys", nil, payload)
}

// APIKeysList calls GET /api/v1/api-keys: List api keys.
func (a *GeneratedAPI) APIKeysList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/api-keys", nil, nil)
}

// APIKeysRevoke calls POST /api/v1/api-keys/{id}/revoke: Revoke an api key.
func (a *GeneratedAPI) APIKeysRevoke(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/api-keys/" + url.PathEscape(id) + "/revoke"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// AuditLogListArgs are the inputs of GeneratedAPI.AuditLogList.
type AuditLogListArgs struct {
	// Action is "action" in the query.
	Action any `query:"action"`

	// Limit is "limit" in the query.
	Limit any `query:"limit"`

	// TargetType is "target_type" in the query.
	TargetType any `query:"target_type"`
}

// AuditLogList calls GET /api/v1/audit-log: List audit log.
func (a *GeneratedAPI) AuditLogList(ctx context.Context, p *AuditLogListArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AuditLogListArgs{}
	}
	q := url.Values{}
	if p.Action != nil {
		q.Set("action", apigenQueryValue(p.Action))
	}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(p.Limit))
	}
	if p.TargetType != nil {
		q.Set("target_type", apigenQueryValue(p.TargetType))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/audit-log", q, nil)
}

// BillingCancelArgs are the inputs of GeneratedAPI.BillingCancel.
type BillingCancelArgs struct {
	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// BillingCancel calls POST /api/v1/billing/cancel: Create a cancel.
func (a *GeneratedAPI) BillingCancel(ctx context.Context, p *BillingCancelArgs) (json.RawMessage, error) {
	if p == nil {
		p = &BillingCancelArgs{}
	}
	payload := apigenBody(p.Body)
	return a.c.apigenRequest(ctx, "POST", "/api/v1/billing/cancel", nil, payload)
}

// BillingCheckoutArgs are the inputs of GeneratedAPI.BillingCheckout.
type BillingCheckoutArgs struct {
	// Plan is "plan" in the body, required. One of: STARTER, GROWTH, SCALE.
	Plan string `json:"plan"`

	// Email is "email" in the body.
	Email *string `json:"email,omitempty"`

	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// BillingCheckout calls POST /api/v1/billing/checkout: Create a checkout.
func (a *GeneratedAPI) BillingCheckout(ctx context.Context, p *BillingCheckoutArgs) (json.RawMessage, error) {
	if p == nil {
		p = &BillingCheckoutArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Plan != "" {
		payload["plan"] = p.Plan
	}
	if p.Email != nil {
		payload["email"] = *p.Email
	}
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if _, ok := payload["plan"]; !ok {
		return nil, apigenMissing("BillingCheckout", "Plan")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/billing/checkout", nil, payload)
}

// BillingInvoicesArgs are the inputs of GeneratedAPI.BillingInvoices.
type BillingInvoicesArgs struct {
	// Cursor is "cursor" in the query.
	Cursor any `query:"cursor"`

	// Limit is "limit" in the query.
	Limit any `query:"limit"`
}

// BillingInvoices calls GET /api/v1/billing/invoices: List invoices.
func (a *GeneratedAPI) BillingInvoices(ctx context.Context, p *BillingInvoicesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &BillingInvoicesArgs{}
	}
	q := url.Values{}
	if p.Cursor != nil {
		q.Set("cursor", apigenQueryValue(p.Cursor))
	}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(p.Limit))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/billing/invoices", q, nil)
}

// BillingPlan calls GET /api/v1/billing/plan: List plan.
func (a *GeneratedAPI) BillingPlan(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/billing/plan", nil, nil)
}

// BillingPlans calls GET /api/v1/billing/plans: Public, no auth.
func (a *GeneratedAPI) BillingPlans(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/billing/plans", nil, nil)
}

// BillingSubscription calls GET /api/v1/billing/subscription: List subscription.
func (a *GeneratedAPI) BillingSubscription(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/billing/subscription", nil, nil)
}

// BillingUsage calls GET /api/v1/billing/usage: List usage.
func (a *GeneratedAPI) BillingUsage(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/billing/usage", nil, nil)
}

// DeliveriesCreateArgs are the inputs of GeneratedAPI.DeliveriesCreate.
type DeliveriesCreateArgs struct {
	// ProductID is "productId" in the body, required.
	ProductID string `json:"productId"`

	// CustomerID is "customerId" in the body, required.
	CustomerID string `json:"customerId"`

	// CheckoutSessionID is "checkoutSessionId" in the body, required.
	CheckoutSessionID string `json:"checkoutSessionId"`

	// MaxDownloads is "maxDownloads" in the body.
	MaxDownloads *int `json:"maxDownloads,omitempty"`

	// ExpiresAt is "expiresAt" in the body.
	ExpiresAt *string `json:"expiresAt,omitempty"`

	// ExternalSource is "externalSource" in the body.
	ExternalSource *string `json:"externalSource,omitempty"`

	// ExternalRef is "externalRef" in the body.
	ExternalRef *string `json:"externalRef,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// DeliveriesCreate calls POST /api/v1/deliveries: Create a delivery.
func (a *GeneratedAPI) DeliveriesCreate(ctx context.Context, p *DeliveriesCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &DeliveriesCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.ProductID != "" {
		payload["productId"] = p.ProductID
	}
	if p.CustomerID != "" {
		payload["customerId"] = p.CustomerID
	}
	if p.CheckoutSessionID != "" {
		payload["checkoutSessionId"] = p.CheckoutSessionID
	}
	if p.MaxDownloads != nil {
		payload["maxDownloads"] = *p.MaxDownloads
	}
	if p.ExpiresAt != nil {
		payload["expiresAt"] = *p.ExpiresAt
	}
	if p.ExternalSource != nil {
		payload["externalSource"] = *p.ExternalSource
	}
	if p.ExternalRef != nil {
		payload["externalRef"] = *p.ExternalRef
	}
	if _, ok := payload["productId"]; !ok {
		return nil, apigenMissing("DeliveriesCreate", "ProductID")
	}
	if _, ok := payload["customerId"]; !ok {
		return nil, apigenMissing("DeliveriesCreate", "CustomerID")
	}
	if _, ok := payload["checkoutSessionId"]; !ok {
		return nil, apigenMissing("DeliveriesCreate", "CheckoutSessionID")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/deliveries", nil, payload)
}

// DeliveriesExtend calls POST /api/v1/deliveries/{id}/extend: Extend the download window 30 days (from now, or the current expiry).
func (a *GeneratedAPI) DeliveriesExtend(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/deliveries/" + url.PathEscape(id) + "/extend"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// DeliveriesGet calls GET /api/v1/deliveries/{id}: Get a delivery.
func (a *GeneratedAPI) DeliveriesGet(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/deliveries/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// DeliveriesList calls GET /api/v1/deliveries: List deliveries.
func (a *GeneratedAPI) DeliveriesList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/deliveries", nil, nil)
}

// DeliveriesResetDownloads calls POST /api/v1/deliveries/{id}/reset-downloads: Reset the download counter so the buyer can download again.
func (a *GeneratedAPI) DeliveriesResetDownloads(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/deliveries/" + url.PathEscape(id) + "/reset-downloads"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// DeliveriesRevoke calls POST /api/v1/deliveries/{id}/revoke: Revoke: expire the delivery now.
func (a *GeneratedAPI) DeliveriesRevoke(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/deliveries/" + url.PathEscape(id) + "/revoke"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// IntegrationsStatus calls GET /api/v1/integrations/status: List status.
func (a *GeneratedAPI) IntegrationsStatus(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/integrations/status", nil, nil)
}

// LicensesActivateArgs are the inputs of GeneratedAPI.LicensesActivate.
type LicensesActivateArgs struct {
	// Key is "key" in the body, required.
	Key string `json:"key"`

	// InstanceID is "instanceId" in the body, required.
	InstanceID string `json:"instanceId"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// LicensesActivate calls POST /api/v1/licenses/activate: /v1/licenses/activate is unauthenticated — buyers' apps call this with the license key directly.
func (a *GeneratedAPI) LicensesActivate(ctx context.Context, p *LicensesActivateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &LicensesActivateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Key != "" {
		payload["key"] = p.Key
	}
	if p.InstanceID != "" {
		payload["instanceId"] = p.InstanceID
	}
	if _, ok := payload["key"]; !ok {
		return nil, apigenMissing("LicensesActivate", "Key")
	}
	if _, ok := payload["instanceId"]; !ok {
		return nil, apigenMissing("LicensesActivate", "InstanceID")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/licenses/activate", nil, payload)
}

// LicensesCreateArgs are the inputs of GeneratedAPI.LicensesCreate.
type LicensesCreateArgs struct {
	// ProductID is "productId" in the body, required.
	ProductID string `json:"productId"`

	// CustomerID is "customerId" in the body, required.
	CustomerID string `json:"customerId"`

	// MaxActivations is "maxActivations" in the body.
	MaxActivations *int `json:"maxActivations,omitempty"`

	// ExpiresAt is "expiresAt" in the body.
	ExpiresAt *string `json:"expiresAt,omitempty"`

	// ExternalSource is "externalSource" in the body.
	ExternalSource *string `json:"externalSource,omitempty"`

	// ExternalRef is "externalRef" in the body.
	ExternalRef *string `json:"externalRef,omitempty"`

	// Key is "key" in the body.
	Key *string `json:"key,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// LicensesCreate calls POST /api/v1/licenses: Create a license.
func (a *GeneratedAPI) LicensesCreate(ctx context.Context, p *LicensesCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &LicensesCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.ProductID != "" {
		payload["productId"] = p.ProductID
	}
	if p.CustomerID != "" {
		payload["customerId"] = p.CustomerID
	}
	if p.MaxActivations != nil {
		payload["maxActivations"] = *p.MaxActivations
	}
	if p.ExpiresAt != nil {
		payload["expiresAt"] = *p.ExpiresAt
	}
	if p.ExternalSource != nil {
		payload["externalSource"] = *p.ExternalSource
	}
	if p.ExternalRef != nil {
		payload["externalRef"] = *p.ExternalRef
	}
	if p.Key != nil {
		payload["key"] = *p.Key
	}
	if _, ok := payload["productId"]; !ok {
		return nil, apigenMissing("LicensesCreate", "ProductID")
	}
	if _, ok := payload["customerId"]; !ok {
		return nil, apigenMissing("LicensesCreate", "CustomerID")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/licenses", nil, payload)
}

// LicensesDeactivateArgs are the inputs of GeneratedAPI.LicensesDeactivate.
type LicensesDeactivateArgs struct {
	// Key is "key" in the body, required.
	Key string `json:"key"`

	// InstanceID is "instanceId" in the body, required.
	InstanceID string `json:"instanceId"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// LicensesDeactivate calls POST /api/v1/licenses/deactivate: Release a previously-activated instance.
func (a *GeneratedAPI) LicensesDeactivate(ctx context.Context, p *LicensesDeactivateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &LicensesDeactivateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Key != "" {
		payload["key"] = p.Key
	}
	if p.InstanceID != "" {
		payload["instanceId"] = p.InstanceID
	}
	if _, ok := payload["key"]; !ok {
		return nil, apigenMissing("LicensesDeactivate", "Key")
	}
	if _, ok := payload["instanceId"]; !ok {
		return nil, apigenMissing("LicensesDeactivate", "InstanceID")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/licenses/deactivate", nil, payload)
}

// LicensesList calls GET /api/v1/licenses: List licenses.
func (a *GeneratedAPI) LicensesList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/licenses", nil, nil)
}

// LicensesLookupArgs are the inputs of GeneratedAPI.LicensesLookup.
type LicensesLookupArgs struct {
	// Key is "key" in the query, required.
	Key string `query:"key"`
}

// LicensesLookup calls GET /api/v1/licenses/lookup: Full license + its activation rows, resolved by key within the merchant's account.
func (a *GeneratedAPI) LicensesLookup(ctx context.Context, p *LicensesLookupArgs) (json.RawMessage, error) {
	if p == nil {
		p = &LicensesLookupArgs{}
	}
	q := url.Values{}
	q.Set("key", p.Key)
	return a.c.apigenRequest(ctx, "GET", "/api/v1/licenses/lookup", q, nil)
}

// LicensesRevoke calls POST /api/v1/licenses/{id}/revoke: Revoke a license.
func (a *GeneratedAPI) LicensesRevoke(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/licenses/" + url.PathEscape(id) + "/revoke"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// LicensesValidateArgs are the inputs of GeneratedAPI.LicensesValidate.
type LicensesValidateArgs struct {
	// Key is "key" in the query, required.
	Key string `query:"key"`

	// ProductID is "productId" in the query.
	ProductID *string `query:"productId"`
}

// LicensesValidate calls GET /api/v1/licenses/validate: Public unauthenticated endpoints — buyers' software calls these with just the license key.
func (a *GeneratedAPI) LicensesValidate(ctx context.Context, p *LicensesValidateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &LicensesValidateArgs{}
	}
	q := url.Values{}
	q.Set("key", p.Key)
	if p.ProductID != nil {
		q.Set("productId", apigenQueryValue(*p.ProductID))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/licenses/validate", q, nil)
}

// ProductsCreateArgs are the inputs of GeneratedAPI.ProductsCreate.
type ProductsCreateArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Sku is "sku" in the body.
	Sku *string `json:"sku,omitempty"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Type is "type" in the body. One of: physical, digital, license.
	Type *string `json:"type,omitempty"`

	// Weight is "weight" in the body.
	Weight *int `json:"weight,omitempty"`

	// Length is "length" in the body.
	Length *int `json:"length,omitempty"`

	// Width is "width" in the body.
	Width *int `json:"width,omitempty"`

	// Height is "height" in the body.
	Height *int `json:"height,omitempty"`

	// LicenseEnabled is "licenseEnabled" in the body.
	LicenseEnabled *bool `json:"licenseEnabled,omitempty"`

	// MaxActivations is "maxActivations" in the body.
	MaxActivations *int `json:"maxActivations,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProductsCreate calls POST /api/v1/products: Create a product.
func (a *GeneratedAPI) ProductsCreate(ctx context.Context, p *ProductsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProductsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.Sku != nil {
		payload["sku"] = *p.Sku
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if p.Type != nil {
		payload["type"] = *p.Type
	}
	if p.Weight != nil {
		payload["weight"] = *p.Weight
	}
	if p.Length != nil {
		payload["length"] = *p.Length
	}
	if p.Width != nil {
		payload["width"] = *p.Width
	}
	if p.Height != nil {
		payload["height"] = *p.Height
	}
	if p.LicenseEnabled != nil {
		payload["licenseEnabled"] = *p.LicenseEnabled
	}
	if p.MaxActivations != nil {
		payload["maxActivations"] = *p.MaxActivations
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("ProductsCreate", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/products", nil, payload)
}

// ProductsCreateVariantsArgs are the inputs of GeneratedAPI.ProductsCreateVariants.
type ProductsCreateVariantsArgs struct {
	// Sku is "sku" in the body.
	Sku *string `json:"sku,omitempty"`

	// Name is "name" in the body, required.
	Name string `json:"name"`

	// PriceCents is "priceCents" in the body.
	PriceCents *int `json:"priceCents,omitempty"`

	// CostCents is "costCents" in the body.
	CostCents *int `json:"costCents,omitempty"`

	// LowStockThreshold is "lowStockThreshold" in the body.
	LowStockThreshold *int `json:"lowStockThreshold,omitempty"`

	// Weight is "weight" in the body.
	Weight *int `json:"weight,omitempty"`

	// IsDefault is "isDefault" in the body.
	IsDefault *bool `json:"isDefault,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProductsCreateVariants calls POST /api/v1/products/{id}/variants: Variants a product.
func (a *GeneratedAPI) ProductsCreateVariants(ctx context.Context, id string, p *ProductsCreateVariantsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProductsCreateVariantsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Sku != nil {
		payload["sku"] = *p.Sku
	}
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.PriceCents != nil {
		payload["priceCents"] = *p.PriceCents
	}
	if p.CostCents != nil {
		payload["costCents"] = *p.CostCents
	}
	if p.LowStockThreshold != nil {
		payload["lowStockThreshold"] = *p.LowStockThreshold
	}
	if p.Weight != nil {
		payload["weight"] = *p.Weight
	}
	if p.IsDefault != nil {
		payload["isDefault"] = *p.IsDefault
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("ProductsCreateVariants", "Name")
	}
	path := "/api/v1/products/" + url.PathEscape(id) + "/variants"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ProductsDelete calls DELETE /api/v1/products/{id}: Delete a product.
func (a *GeneratedAPI) ProductsDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/products/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// ProductsDeleteVariants calls DELETE /api/v1/products/{id}/variants/{variantId}: Delete a variant.
func (a *GeneratedAPI) ProductsDeleteVariants(ctx context.Context, id string, variantID string) (json.RawMessage, error) {
	path := "/api/v1/products/" + url.PathEscape(id) + "/variants/" + url.PathEscape(variantID)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// ProductsGet calls GET /api/v1/products/{id}: Get a product.
func (a *GeneratedAPI) ProductsGet(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/products/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ProductsListArgs are the inputs of GeneratedAPI.ProductsList.
type ProductsListArgs struct {
	// Archived is "archived" in the query.
	Archived any `query:"archived"`
}

// ProductsList calls GET /api/v1/products: List products.
func (a *GeneratedAPI) ProductsList(ctx context.Context, p *ProductsListArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProductsListArgs{}
	}
	q := url.Values{}
	if p.Archived != nil {
		q.Set("archived", apigenQueryValue(p.Archived))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/products", q, nil)
}

// ProductsUpdateArgs are the inputs of GeneratedAPI.ProductsUpdate.
type ProductsUpdateArgs struct {
	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// Sku is "sku" in the body.
	Sku *string `json:"sku,omitempty"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Type is "type" in the body. One of: physical, digital, license.
	Type *string `json:"type,omitempty"`

	// Weight is "weight" in the body.
	Weight *int `json:"weight,omitempty"`

	// Length is "length" in the body.
	Length *int `json:"length,omitempty"`

	// Width is "width" in the body.
	Width *int `json:"width,omitempty"`

	// Height is "height" in the body.
	Height *int `json:"height,omitempty"`

	// LicenseEnabled is "licenseEnabled" in the body.
	LicenseEnabled *bool `json:"licenseEnabled,omitempty"`

	// MaxActivations is "maxActivations" in the body.
	MaxActivations *int `json:"maxActivations,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProductsUpdate calls PATCH /api/v1/products/{id}: Update a product.
func (a *GeneratedAPI) ProductsUpdate(ctx context.Context, id string, p *ProductsUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProductsUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.Sku != nil {
		payload["sku"] = *p.Sku
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if p.Type != nil {
		payload["type"] = *p.Type
	}
	if p.Weight != nil {
		payload["weight"] = *p.Weight
	}
	if p.Length != nil {
		payload["length"] = *p.Length
	}
	if p.Width != nil {
		payload["width"] = *p.Width
	}
	if p.Height != nil {
		payload["height"] = *p.Height
	}
	if p.LicenseEnabled != nil {
		payload["licenseEnabled"] = *p.LicenseEnabled
	}
	if p.MaxActivations != nil {
		payload["maxActivations"] = *p.MaxActivations
	}
	path := "/api/v1/products/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// ProductsUpdateVariantsArgs are the inputs of GeneratedAPI.ProductsUpdateVariants.
type ProductsUpdateVariantsArgs struct {
	// Sku is "sku" in the body.
	Sku *string `json:"sku,omitempty"`

	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// PriceCents is "priceCents" in the body.
	PriceCents *int `json:"priceCents,omitempty"`

	// CostCents is "costCents" in the body.
	CostCents *int `json:"costCents,omitempty"`

	// LowStockThreshold is "lowStockThreshold" in the body.
	LowStockThreshold *int `json:"lowStockThreshold,omitempty"`

	// Weight is "weight" in the body.
	Weight *int `json:"weight,omitempty"`

	// IsDefault is "isDefault" in the body.
	IsDefault *bool `json:"isDefault,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ProductsUpdateVariants calls PATCH /api/v1/products/{id}/variants/{variantId}: Update a variant.
func (a *GeneratedAPI) ProductsUpdateVariants(ctx context.Context, id string, variantID string, p *ProductsUpdateVariantsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ProductsUpdateVariantsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Sku != nil {
		payload["sku"] = *p.Sku
	}
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.PriceCents != nil {
		payload["priceCents"] = *p.PriceCents
	}
	if p.CostCents != nil {
		payload["costCents"] = *p.CostCents
	}
	if p.LowStockThreshold != nil {
		payload["lowStockThreshold"] = *p.LowStockThreshold
	}
	if p.Weight != nil {
		payload["weight"] = *p.Weight
	}
	if p.IsDefault != nil {
		payload["isDefault"] = *p.IsDefault
	}
	path := "/api/v1/products/" + url.PathEscape(id) + "/variants/" + url.PathEscape(variantID)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// ShipmentsCancelArgs are the inputs of GeneratedAPI.ShipmentsCancel.
type ShipmentsCancelArgs struct {
	// Reason is "reason" in the body.
	Reason any `json:"reason,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShipmentsCancel calls POST /api/v1/shipments/{id}/cancel: Cancel a booking the courier hasn't collected yet, and give back the shipping credit confirm-pickup consumed.
func (a *GeneratedAPI) ShipmentsCancel(ctx context.Context, id string, p *ShipmentsCancelArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShipmentsCancelArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Reason != nil {
		payload["reason"] = p.Reason
	}
	path := "/api/v1/shipments/" + url.PathEscape(id) + "/cancel"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ShipmentsConfirmPickup calls POST /api/v1/shipments/{id}/confirm-pickup: F-004: Merchant clicks "Book courier" once the parcel is actually ready.
func (a *GeneratedAPI) ShipmentsConfirmPickup(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/shipments/" + url.PathEscape(id) + "/confirm-pickup"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// ShipmentsCreateArgs are the inputs of GeneratedAPI.ShipmentsCreate.
type ShipmentsCreateArgs struct {
	// ProductID is "productId" in the body.
	ProductID *string `json:"productId,omitempty"`

	// CheckoutSessionID is "checkoutSessionId" in the body.
	CheckoutSessionID *string `json:"checkoutSessionId,omitempty"`

	// CustomerID is "customerId" in the body.
	CustomerID *string `json:"customerId,omitempty"`

	// CustomerEmail is "customerEmail" in the body.
	CustomerEmail *string `json:"customerEmail,omitempty"`

	// CourierCode is "courierCode" in the body, required.
	CourierCode string `json:"courierCode"`

	// CourierServiceCode is "courierServiceCode" in the body, required.
	CourierServiceCode string `json:"courierServiceCode"`

	// CourierType is "courierType" in the body, required.
	CourierType string `json:"courierType"`

	// Price is "price" in the body, required.
	Price int `json:"price"`

	// Insurance is "insurance" in the body.
	Insurance *int `json:"insurance,omitempty"`

	// Insured is "insured" in the body.
	Insured *bool `json:"insured,omitempty"`

	// Origin is "origin" in the body, required.
	Origin map[string]any `json:"origin"`

	// Destination is "destination" in the body, required.
	Destination map[string]any `json:"destination"`

	// Items is "items" in the body, required.
	Items []any `json:"items"`

	// ExternalSource is "externalSource" in the body.
	ExternalSource *string `json:"externalSource,omitempty"`

	// ExternalRef is "externalRef" in the body.
	ExternalRef *string `json:"externalRef,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShipmentsCreate calls POST /api/v1/shipments: Create a shipment.
func (a *GeneratedAPI) ShipmentsCreate(ctx context.Context, p *ShipmentsCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShipmentsCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.ProductID != nil {
		payload["productId"] = *p.ProductID
	}
	if p.CheckoutSessionID != nil {
		payload["checkoutSessionId"] = *p.CheckoutSessionID
	}
	if p.CustomerID != nil {
		payload["customerId"] = *p.CustomerID
	}
	if p.CustomerEmail != nil {
		payload["customerEmail"] = *p.CustomerEmail
	}
	if p.CourierCode != "" {
		payload["courierCode"] = p.CourierCode
	}
	if p.CourierServiceCode != "" {
		payload["courierServiceCode"] = p.CourierServiceCode
	}
	if p.CourierType != "" {
		payload["courierType"] = p.CourierType
	}
	if _, ok := payload["price"]; !ok || p.Price != 0 {
		payload["price"] = p.Price
	}
	if p.Insurance != nil {
		payload["insurance"] = *p.Insurance
	}
	if p.Insured != nil {
		payload["insured"] = *p.Insured
	}
	if p.Origin != nil {
		payload["origin"] = p.Origin
	}
	if p.Destination != nil {
		payload["destination"] = p.Destination
	}
	if p.Items != nil {
		payload["items"] = p.Items
	}
	if p.ExternalSource != nil {
		payload["externalSource"] = *p.ExternalSource
	}
	if p.ExternalRef != nil {
		payload["externalRef"] = *p.ExternalRef
	}
	if _, ok := payload["courierCode"]; !ok {
		return nil, apigenMissing("ShipmentsCreate", "CourierCode")
	}
	if _, ok := payload["courierServiceCode"]; !ok {
		return nil, apigenMissing("ShipmentsCreate", "CourierServiceCode")
	}
	if _, ok := payload["courierType"]; !ok {
		return nil, apigenMissing("ShipmentsCreate", "CourierType")
	}
	if _, ok := payload["origin"]; !ok {
		return nil, apigenMissing("ShipmentsCreate", "Origin")
	}
	if _, ok := payload["destination"]; !ok {
		return nil, apigenMissing("ShipmentsCreate", "Destination")
	}
	if _, ok := payload["items"]; !ok {
		return nil, apigenMissing("ShipmentsCreate", "Items")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/shipments", nil, payload)
}

// ShipmentsGet calls GET /api/v1/shipments/{id}: Get a shipment.
func (a *GeneratedAPI) ShipmentsGet(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/shipments/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ShipmentsLabelArgs are the inputs of GeneratedAPI.ShipmentsLabel.
type ShipmentsLabelArgs struct {
	// Size is "size" in the query. One of: a4, thermal-80x100, thermal-100x150.
	Size *string `query:"size"`

	// ShowSenderPhone is "showSenderPhone" in the query. One of: true, false.
	ShowSenderPhone *string `query:"showSenderPhone"`

	// ShowRecipientPhone is "showRecipientPhone" in the query. One of: true, false.
	ShowRecipientPhone *string `query:"showRecipientPhone"`

	// MaskRecipientName is "maskRecipientName" in the query. One of: true, false.
	MaskRecipientName *string `query:"maskRecipientName"`

	// MaskRecipientPhone is "maskRecipientPhone" in the query. One of: true, false.
	MaskRecipientPhone *string `query:"maskRecipientPhone"`

	// ShowShippingCost is "showShippingCost" in the query. One of: true, false.
	ShowShippingCost *string `query:"showShippingCost"`

	// ShowInsurance is "showInsurance" in the query. One of: true, false.
	ShowInsurance *string `query:"showInsurance"`

	// ShowItems is "showItems" in the query. One of: true, false.
	ShowItems *string `query:"showItems"`

	// ShowItemDescriptions is "showItemDescriptions" in the query. One of: true, false.
	ShowItemDescriptions *string `query:"showItemDescriptions"`

	// ShowItemSkus is "showItemSkus" in the query. One of: true, false.
	ShowItemSkus *string `query:"showItemSkus"`
}

// ShipmentsLabel calls GET /api/v1/shipments/{id}/label: Biteship deliberately has no shipping-label API.
func (a *GeneratedAPI) ShipmentsLabel(ctx context.Context, id string, p *ShipmentsLabelArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShipmentsLabelArgs{}
	}
	q := url.Values{}
	if p.Size != nil {
		q.Set("size", apigenQueryValue(*p.Size))
	}
	if p.ShowSenderPhone != nil {
		q.Set("showSenderPhone", apigenQueryValue(*p.ShowSenderPhone))
	}
	if p.ShowRecipientPhone != nil {
		q.Set("showRecipientPhone", apigenQueryValue(*p.ShowRecipientPhone))
	}
	if p.MaskRecipientName != nil {
		q.Set("maskRecipientName", apigenQueryValue(*p.MaskRecipientName))
	}
	if p.MaskRecipientPhone != nil {
		q.Set("maskRecipientPhone", apigenQueryValue(*p.MaskRecipientPhone))
	}
	if p.ShowShippingCost != nil {
		q.Set("showShippingCost", apigenQueryValue(*p.ShowShippingCost))
	}
	if p.ShowInsurance != nil {
		q.Set("showInsurance", apigenQueryValue(*p.ShowInsurance))
	}
	if p.ShowItems != nil {
		q.Set("showItems", apigenQueryValue(*p.ShowItems))
	}
	if p.ShowItemDescriptions != nil {
		q.Set("showItemDescriptions", apigenQueryValue(*p.ShowItemDescriptions))
	}
	if p.ShowItemSkus != nil {
		q.Set("showItemSkus", apigenQueryValue(*p.ShowItemSkus))
	}
	path := "/api/v1/shipments/" + url.PathEscape(id) + "/label"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// ShipmentsListArgs are the inputs of GeneratedAPI.ShipmentsList.
type ShipmentsListArgs struct {
	// Status is "status" in the query.
	Status any `query:"status"`
}

// ShipmentsList calls GET /api/v1/shipments: List shipments.
func (a *GeneratedAPI) ShipmentsList(ctx context.Context, p *ShipmentsListArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShipmentsListArgs{}
	}
	q := url.Values{}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(p.Status))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/shipments", q, nil)
}

// ShipmentsRebookArgs are the inputs of GeneratedAPI.ShipmentsRebook.
type ShipmentsRebookArgs struct {
	// CourierCode is "courierCode" in the body.
	CourierCode *string `json:"courierCode,omitempty"`

	// CourierServiceCode is "courierServiceCode" in the body.
	CourierServiceCode *string `json:"courierServiceCode,omitempty"`

	// CourierType is "courierType" in the body.
	CourierType *string `json:"courierType,omitempty"`

	// Price is "price" in the body.
	Price *int `json:"price,omitempty"`

	// Insured is "insured" in the body.
	Insured *bool `json:"insured,omitempty"`

	// Insurance is "insurance" in the body.
	Insurance *int `json:"insurance,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShipmentsRebook calls POST /api/v1/shipments/{id}/rebook: Rebook a shipment.
func (a *GeneratedAPI) ShipmentsRebook(ctx context.Context, id string, p *ShipmentsRebookArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShipmentsRebookArgs{}
	}
	payload := apigenBody(p.Body)
	if p.CourierCode != nil {
		payload["courierCode"] = *p.CourierCode
	}
	if p.CourierServiceCode != nil {
		payload["courierServiceCode"] = *p.CourierServiceCode
	}
	if p.CourierType != nil {
		payload["courierType"] = *p.CourierType
	}
	if p.Price != nil {
		payload["price"] = *p.Price
	}
	if p.Insured != nil {
		payload["insured"] = *p.Insured
	}
	if p.Insurance != nil {
		payload["insurance"] = *p.Insurance
	}
	path := "/api/v1/shipments/" + url.PathEscape(id) + "/rebook"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ShipmentsTracking calls GET /api/v1/shipments/{id}/tracking: F-008: live tracking detail (driver, status history, ETA) from Biteship.
func (a *GeneratedAPI) ShipmentsTracking(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/shipments/" + url.PathEscape(id) + "/tracking"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ShippingAreasArgs are the inputs of GeneratedAPI.ShippingAreas.
type ShippingAreasArgs struct {
	// Q is "q" in the query.
	Q any `query:"q"`
}

// ShippingAreas calls GET /api/v1/shipping/areas: List areas.
func (a *GeneratedAPI) ShippingAreas(ctx context.Context, p *ShippingAreasArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingAreasArgs{}
	}
	q := url.Values{}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(p.Q))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/shipping/areas", q, nil)
}

// ShippingConfig calls GET /api/v1/shipping/config: List config.
func (a *GeneratedAPI) ShippingConfig(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/shipping/config", nil, nil)
}

// ShippingCouriers calls GET /api/v1/shipping/couriers: In Fulkruma we still gate this behind requireAuth: the dashboard always has a session, and we want per-merchant API key resolution.
func (a *GeneratedAPI) ShippingCouriers(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/shipping/couriers", nil, nil)
}

// ShippingGetShipments calls GET /api/v1/shipping/shipments/{id}: Get a shipment.
func (a *GeneratedAPI) ShippingGetShipments(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/shipping/shipments/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// ShippingOrigin calls GET /api/v1/shipping/origin: List origin.
func (a *GeneratedAPI) ShippingOrigin(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/shipping/origin", nil, nil)
}

// ShippingRatesArgs are the inputs of GeneratedAPI.ShippingRates.
type ShippingRatesArgs struct {
	// Destination is "destination" in the body, required.
	Destination map[string]any `json:"destination"`

	// Items is "items" in the body, required.
	Items []any `json:"items"`

	// Insurance is "insurance" in the body.
	Insurance *bool `json:"insurance,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShippingRates calls POST /api/v1/shipping/rates: Create a rate.
func (a *GeneratedAPI) ShippingRates(ctx context.Context, p *ShippingRatesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingRatesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Destination != nil {
		payload["destination"] = p.Destination
	}
	if p.Items != nil {
		payload["items"] = p.Items
	}
	if p.Insurance != nil {
		payload["insurance"] = *p.Insurance
	}
	if _, ok := payload["destination"]; !ok {
		return nil, apigenMissing("ShippingRates", "Destination")
	}
	if _, ok := payload["items"]; !ok {
		return nil, apigenMissing("ShippingRates", "Items")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/shipping/rates", nil, payload)
}

// ShippingSetConfigArgs are the inputs of GeneratedAPI.ShippingSetConfig.
type ShippingSetConfigArgs struct {
	// APIKey is "apiKey" in the body.
	APIKey *string `json:"apiKey,omitempty"`

	// DefaultOriginID is "defaultOriginId" in the body.
	DefaultOriginID *string `json:"defaultOriginId,omitempty"`

	// EnabledCouriers is "enabledCouriers" in the body.
	EnabledCouriers []string `json:"enabledCouriers,omitempty"`

	// DefaultCourier is "defaultCourier" in the body.
	DefaultCourier *string `json:"defaultCourier,omitempty"`

	// Active is "active" in the body.
	Active *bool `json:"active,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShippingSetConfig calls PUT /api/v1/shipping/config: Set config.
func (a *GeneratedAPI) ShippingSetConfig(ctx context.Context, p *ShippingSetConfigArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingSetConfigArgs{}
	}
	payload := apigenBody(p.Body)
	if p.APIKey != nil {
		payload["apiKey"] = *p.APIKey
	}
	if p.DefaultOriginID != nil {
		payload["defaultOriginId"] = *p.DefaultOriginID
	}
	if p.EnabledCouriers != nil {
		payload["enabledCouriers"] = p.EnabledCouriers
	}
	if p.DefaultCourier != nil {
		payload["defaultCourier"] = *p.DefaultCourier
	}
	if p.Active != nil {
		payload["active"] = *p.Active
	}
	return a.c.apigenRequest(ctx, "PUT", "/api/v1/shipping/config", nil, payload)
}

// ShippingShipmentsArgs are the inputs of GeneratedAPI.ShippingShipments.
type ShippingShipmentsArgs struct {
	// Cursor is "cursor" in the query.
	Cursor any `query:"cursor"`

	// Limit is "limit" in the query.
	Limit any `query:"limit"`

	// Status is "status" in the query.
	Status any `query:"status"`
}

// ShippingShipments calls GET /api/v1/shipping/shipments: List shipments.
func (a *GeneratedAPI) ShippingShipments(ctx context.Context, p *ShippingShipmentsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingShipmentsArgs{}
	}
	q := url.Values{}
	if p.Cursor != nil {
		q.Set("cursor", apigenQueryValue(p.Cursor))
	}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(p.Limit))
	}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(p.Status))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/shipping/shipments", q, nil)
}

// ShippingShipmentsCancelArgs are the inputs of GeneratedAPI.ShippingShipmentsCancel.
type ShippingShipmentsCancelArgs struct {
	// Reason is "reason" in the body.
	Reason any `json:"reason,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShippingShipmentsCancel calls POST /api/v1/shipping/shipments/{id}/cancel: Legacy namespace.
func (a *GeneratedAPI) ShippingShipmentsCancel(ctx context.Context, id string, p *ShippingShipmentsCancelArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingShipmentsCancelArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Reason != nil {
		payload["reason"] = p.Reason
	}
	path := "/api/v1/shipping/shipments/" + url.PathEscape(id) + "/cancel"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ShippingShipmentsLabelArgs are the inputs of GeneratedAPI.ShippingShipmentsLabel.
type ShippingShipmentsLabelArgs struct {
	// Size is "size" in the query.
	Size any `query:"size"`
}

// ShippingShipmentsLabel calls GET /api/v1/shipping/shipments/{id}/label: Legacy shipping namespace.
func (a *GeneratedAPI) ShippingShipmentsLabel(ctx context.Context, id string, p *ShippingShipmentsLabelArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingShipmentsLabelArgs{}
	}
	q := url.Values{}
	if p.Size != nil {
		q.Set("size", apigenQueryValue(p.Size))
	}
	path := "/api/v1/shipping/shipments/" + url.PathEscape(id) + "/label"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// ShippingShipmentsRebookArgs are the inputs of GeneratedAPI.ShippingShipmentsRebook.
type ShippingShipmentsRebookArgs struct {
	// CourierCode is "courierCode" in the body.
	CourierCode *string `json:"courierCode,omitempty"`

	// CourierServiceCode is "courierServiceCode" in the body.
	CourierServiceCode *string `json:"courierServiceCode,omitempty"`

	// CourierType is "courierType" in the body.
	CourierType *string `json:"courierType,omitempty"`

	// Price is "price" in the body.
	Price *int `json:"price,omitempty"`

	// Insured is "insured" in the body.
	Insured *bool `json:"insured,omitempty"`

	// Insurance is "insurance" in the body.
	Insurance *int `json:"insurance,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShippingShipmentsRebook calls POST /api/v1/shipping/shipments/{id}/rebook: Legacy-namespace twin of /shipments/:id/rebook.
func (a *GeneratedAPI) ShippingShipmentsRebook(ctx context.Context, id string, p *ShippingShipmentsRebookArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingShipmentsRebookArgs{}
	}
	payload := apigenBody(p.Body)
	if p.CourierCode != nil {
		payload["courierCode"] = *p.CourierCode
	}
	if p.CourierServiceCode != nil {
		payload["courierServiceCode"] = *p.CourierServiceCode
	}
	if p.CourierType != nil {
		payload["courierType"] = *p.CourierType
	}
	if p.Price != nil {
		payload["price"] = *p.Price
	}
	if p.Insured != nil {
		payload["insured"] = *p.Insured
	}
	if p.Insurance != nil {
		payload["insurance"] = *p.Insurance
	}
	path := "/api/v1/shipping/shipments/" + url.PathEscape(id) + "/rebook"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// ShippingTrackArgs are the inputs of GeneratedAPI.ShippingTrack.
type ShippingTrackArgs struct {
	// Courier is "courier" in the query, required.
	Courier any `query:"courier"`
}

// ShippingTrack calls GET /api/v1/shipping/track/{waybillId}: Get a track.
func (a *GeneratedAPI) ShippingTrack(ctx context.Context, waybillID string, p *ShippingTrackArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingTrackArgs{}
	}
	q := url.Values{}
	if p.Courier != nil {
		q.Set("courier", apigenQueryValue(p.Courier))
	}
	path := "/api/v1/shipping/track/" + url.PathEscape(waybillID)
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// ShippingUpdateOriginArgs are the inputs of GeneratedAPI.ShippingUpdateOrigin.
type ShippingUpdateOriginArgs struct {
	// Address is "address" in the body, required.
	Address string `json:"address"`

	// Province is "province" in the body.
	Province *string `json:"province,omitempty"`

	// City is "city" in the body.
	City *string `json:"city,omitempty"`

	// District is "district" in the body.
	District *string `json:"district,omitempty"`

	// Village is "village" in the body.
	Village *string `json:"village,omitempty"`

	// Postal is "postal" in the body.
	Postal *string `json:"postal,omitempty"`

	// AreaID is "areaId" in the body.
	AreaID *string `json:"areaId,omitempty"`

	// Lat is "lat" in the body.
	Lat *float64 `json:"lat,omitempty"`

	// Lng is "lng" in the body.
	Lng *float64 `json:"lng,omitempty"`

	// Note is "note" in the body.
	Note *string `json:"note,omitempty"`

	// ContactName is "contactName" in the body, required.
	ContactName string `json:"contactName"`

	// ContactPhone is "contactPhone" in the body, required.
	ContactPhone string `json:"contactPhone"`

	// Couriers is "couriers" in the body.
	Couriers []string `json:"couriers,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShippingUpdateOrigin calls PATCH /api/v1/shipping/origin: Update origin.
func (a *GeneratedAPI) ShippingUpdateOrigin(ctx context.Context, p *ShippingUpdateOriginArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingUpdateOriginArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Address != "" {
		payload["address"] = p.Address
	}
	if p.Province != nil {
		payload["province"] = *p.Province
	}
	if p.City != nil {
		payload["city"] = *p.City
	}
	if p.District != nil {
		payload["district"] = *p.District
	}
	if p.Village != nil {
		payload["village"] = *p.Village
	}
	if p.Postal != nil {
		payload["postal"] = *p.Postal
	}
	if p.AreaID != nil {
		payload["areaId"] = *p.AreaID
	}
	if p.Lat != nil {
		payload["lat"] = *p.Lat
	}
	if p.Lng != nil {
		payload["lng"] = *p.Lng
	}
	if p.Note != nil {
		payload["note"] = *p.Note
	}
	if p.ContactName != "" {
		payload["contactName"] = p.ContactName
	}
	if p.ContactPhone != "" {
		payload["contactPhone"] = p.ContactPhone
	}
	if p.Couriers != nil {
		payload["couriers"] = p.Couriers
	}
	if _, ok := payload["address"]; !ok {
		return nil, apigenMissing("ShippingUpdateOrigin", "Address")
	}
	if _, ok := payload["contactName"]; !ok {
		return nil, apigenMissing("ShippingUpdateOrigin", "ContactName")
	}
	if _, ok := payload["contactPhone"]; !ok {
		return nil, apigenMissing("ShippingUpdateOrigin", "ContactPhone")
	}
	return a.c.apigenRequest(ctx, "PATCH", "/api/v1/shipping/origin", nil, payload)
}

// ShippingCreditsAdjustArgs are the inputs of GeneratedAPI.ShippingCreditsAdjust.
type ShippingCreditsAdjustArgs struct {
	// Amount is "amount" in the body, required.
	Amount int `json:"amount"`

	// Kind is "kind" in the body, required. One of: manual_adjustment, shipment_refund.
	Kind string `json:"kind"`

	// ShipmentID is "shipmentId" in the body.
	ShipmentID *string `json:"shipmentId,omitempty"`

	// ExternalRef is "externalRef" in the body.
	ExternalRef *string `json:"externalRef,omitempty"`

	// Memo is "memo" in the body.
	Memo *string `json:"memo,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShippingCreditsAdjust calls POST /api/v1/shipping-credits/adjust: Create an adjust.
func (a *GeneratedAPI) ShippingCreditsAdjust(ctx context.Context, p *ShippingCreditsAdjustArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingCreditsAdjustArgs{}
	}
	payload := apigenBody(p.Body)
	if _, ok := payload["amount"]; !ok || p.Amount != 0 {
		payload["amount"] = p.Amount
	}
	if p.Kind != "" {
		payload["kind"] = p.Kind
	}
	if p.ShipmentID != nil {
		payload["shipmentId"] = *p.ShipmentID
	}
	if p.ExternalRef != nil {
		payload["externalRef"] = *p.ExternalRef
	}
	if p.Memo != nil {
		payload["memo"] = *p.Memo
	}
	if _, ok := payload["kind"]; !ok {
		return nil, apigenMissing("ShippingCreditsAdjust", "Kind")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/shipping-credits/adjust", nil, payload)
}

// ShippingCreditsCheckoutArgs are the inputs of GeneratedAPI.ShippingCreditsCheckout.
type ShippingCreditsCheckoutArgs struct {
	// Amount is "amount" in the body, required.
	Amount int `json:"amount"`

	// Email is "email" in the body.
	Email *string `json:"email,omitempty"`

	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShippingCreditsCheckout calls POST /api/v1/shipping-credits/checkout: Create a checkout.
func (a *GeneratedAPI) ShippingCreditsCheckout(ctx context.Context, p *ShippingCreditsCheckoutArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingCreditsCheckoutArgs{}
	}
	payload := apigenBody(p.Body)
	if _, ok := payload["amount"]; !ok || p.Amount != 0 {
		payload["amount"] = p.Amount
	}
	if p.Email != nil {
		payload["email"] = *p.Email
	}
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/shipping-credits/checkout", nil, payload)
}

// ShippingCreditsList calls GET /api/v1/shipping-credits: Balance for the calling merchant.
func (a *GeneratedAPI) ShippingCreditsList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/shipping-credits", nil, nil)
}

// ShippingCreditsTopupArgs are the inputs of GeneratedAPI.ShippingCreditsTopup.
type ShippingCreditsTopupArgs struct {
	// Amount is "amount" in the body, required.
	Amount int `json:"amount"`

	// ExternalRef is "externalRef" in the body.
	ExternalRef *string `json:"externalRef,omitempty"`

	// Memo is "memo" in the body.
	Memo *string `json:"memo,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// ShippingCreditsTopup calls POST /api/v1/shipping-credits/topup: Create a topup.
func (a *GeneratedAPI) ShippingCreditsTopup(ctx context.Context, p *ShippingCreditsTopupArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingCreditsTopupArgs{}
	}
	payload := apigenBody(p.Body)
	if _, ok := payload["amount"]; !ok || p.Amount != 0 {
		payload["amount"] = p.Amount
	}
	if p.ExternalRef != nil {
		payload["externalRef"] = *p.ExternalRef
	}
	if p.Memo != nil {
		payload["memo"] = *p.Memo
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/shipping-credits/topup", nil, payload)
}

// ShippingCreditsTransactionsArgs are the inputs of GeneratedAPI.ShippingCreditsTransactions.
type ShippingCreditsTransactionsArgs struct {
	// Limit is "limit" in the query.
	Limit *int `query:"limit"`

	// Cursor is "cursor" in the query.
	Cursor *string `query:"cursor"`
}

// ShippingCreditsTransactions calls GET /api/v1/shipping-credits/transactions: List transactions.
func (a *GeneratedAPI) ShippingCreditsTransactions(ctx context.Context, p *ShippingCreditsTransactionsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &ShippingCreditsTransactionsArgs{}
	}
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(*p.Limit))
	}
	if p.Cursor != nil {
		q.Set("cursor", apigenQueryValue(*p.Cursor))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/shipping-credits/transactions", q, nil)
}

// StatsOverview calls GET /api/v1/stats/overview: Powers the /dashboard overview tiles.
func (a *GeneratedAPI) StatsOverview(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/stats/overview", nil, nil)
}

// StockAdjustArgs are the inputs of GeneratedAPI.StockAdjust.
type StockAdjustArgs struct {
	// VariantID is "variantId" in the body, required.
	VariantID string `json:"variantId"`

	// WarehouseID is "warehouseId" in the body, required.
	WarehouseID string `json:"warehouseId"`

	// Delta is "delta" in the body, required.
	Delta int `json:"delta"`

	// Reason is "reason" in the body, required. One of: manual_adjust, initial_stock, transfer_in, transfer_out, damaged, returned_to_supplier, refund_restock, import.
	Reason string `json:"reason"`

	// Note is "note" in the body.
	Note *string `json:"note,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// StockAdjust calls POST /api/v1/stock/adjust: Create an adjust.
func (a *GeneratedAPI) StockAdjust(ctx context.Context, p *StockAdjustArgs) (json.RawMessage, error) {
	if p == nil {
		p = &StockAdjustArgs{}
	}
	payload := apigenBody(p.Body)
	if p.VariantID != "" {
		payload["variantId"] = p.VariantID
	}
	if p.WarehouseID != "" {
		payload["warehouseId"] = p.WarehouseID
	}
	if _, ok := payload["delta"]; !ok || p.Delta != 0 {
		payload["delta"] = p.Delta
	}
	if p.Reason != "" {
		payload["reason"] = p.Reason
	}
	if p.Note != nil {
		payload["note"] = *p.Note
	}
	if _, ok := payload["variantId"]; !ok {
		return nil, apigenMissing("StockAdjust", "VariantID")
	}
	if _, ok := payload["warehouseId"]; !ok {
		return nil, apigenMissing("StockAdjust", "WarehouseID")
	}
	if _, ok := payload["reason"]; !ok {
		return nil, apigenMissing("StockAdjust", "Reason")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/stock/adjust", nil, payload)
}

// StockLevelsArgs are the inputs of GeneratedAPI.StockLevels.
type StockLevelsArgs struct {
	// VariantID is "variant_id" in the query.
	VariantID any `query:"variant_id"`
}

// StockLevels calls GET /api/v1/stock/levels: List levels.
func (a *GeneratedAPI) StockLevels(ctx context.Context, p *StockLevelsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &StockLevelsArgs{}
	}
	q := url.Values{}
	if p.VariantID != nil {
		q.Set("variant_id", apigenQueryValue(p.VariantID))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/stock/levels", q, nil)
}

// StockMovementsArgs are the inputs of GeneratedAPI.StockMovements.
type StockMovementsArgs struct {
	// VariantID is "variant_id" in the query.
	VariantID any `query:"variant_id"`
}

// StockMovements calls GET /api/v1/stock/movements: List movements.
func (a *GeneratedAPI) StockMovements(ctx context.Context, p *StockMovementsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &StockMovementsArgs{}
	}
	q := url.Values{}
	if p.VariantID != nil {
		q.Set("variant_id", apigenQueryValue(p.VariantID))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/stock/movements", q, nil)
}

// StockReservations calls GET /api/v1/stock/reservations: List reservations.
func (a *GeneratedAPI) StockReservations(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/stock/reservations", nil, nil)
}

// WarehousesCreateArgs are the inputs of GeneratedAPI.WarehousesCreate.
type WarehousesCreateArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Address is "address" in the body.
	Address *string `json:"address,omitempty"`

	// City is "city" in the body.
	City *string `json:"city,omitempty"`

	// Postal is "postal" in the body.
	Postal *string `json:"postal,omitempty"`

	// Lat is "lat" in the body.
	Lat *float64 `json:"lat,omitempty"`

	// Lng is "lng" in the body.
	Lng *float64 `json:"lng,omitempty"`

	// Phone is "phone" in the body.
	Phone *string `json:"phone,omitempty"`

	// IsDefault is "isDefault" in the body.
	IsDefault *bool `json:"isDefault,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// WarehousesCreate calls POST /api/v1/warehouses: Create a warehouse.
func (a *GeneratedAPI) WarehousesCreate(ctx context.Context, p *WarehousesCreateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &WarehousesCreateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.Address != nil {
		payload["address"] = *p.Address
	}
	if p.City != nil {
		payload["city"] = *p.City
	}
	if p.Postal != nil {
		payload["postal"] = *p.Postal
	}
	if p.Lat != nil {
		payload["lat"] = *p.Lat
	}
	if p.Lng != nil {
		payload["lng"] = *p.Lng
	}
	if p.Phone != nil {
		payload["phone"] = *p.Phone
	}
	if p.IsDefault != nil {
		payload["isDefault"] = *p.IsDefault
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("WarehousesCreate", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/warehouses", nil, payload)
}

// WarehousesDelete calls DELETE /api/v1/warehouses/{id}: Delete a warehouse.
func (a *GeneratedAPI) WarehousesDelete(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/warehouses/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// WarehousesList calls GET /api/v1/warehouses: List warehouses.
func (a *GeneratedAPI) WarehousesList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/warehouses", nil, nil)
}

// WarehousesUpdateArgs are the inputs of GeneratedAPI.WarehousesUpdate.
type WarehousesUpdateArgs struct {
	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// Address is "address" in the body.
	Address *string `json:"address,omitempty"`

	// City is "city" in the body.
	City *string `json:"city,omitempty"`

	// Postal is "postal" in the body.
	Postal *string `json:"postal,omitempty"`

	// Lat is "lat" in the body.
	Lat *float64 `json:"lat,omitempty"`

	// Lng is "lng" in the body.
	Lng *float64 `json:"lng,omitempty"`

	// Phone is "phone" in the body.
	Phone *string `json:"phone,omitempty"`

	// IsDefault is "isDefault" in the body.
	IsDefault *bool `json:"isDefault,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// WarehousesUpdate calls PATCH /api/v1/warehouses/{id}: Update a warehouse.
func (a *GeneratedAPI) WarehousesUpdate(ctx context.Context, id string, p *WarehousesUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &WarehousesUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.Address != nil {
		payload["address"] = *p.Address
	}
	if p.City != nil {
		payload["city"] = *p.City
	}
	if p.Postal != nil {
		payload["postal"] = *p.Postal
	}
	if p.Lat != nil {
		payload["lat"] = *p.Lat
	}
	if p.Lng != nil {
		payload["lng"] = *p.Lng
	}
	if p.Phone != nil {
		payload["phone"] = *p.Phone
	}
	if p.IsDefault != nil {
		payload["isDefault"] = *p.IsDefault
	}
	path := "/api/v1/warehouses/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// WebhooksCreateEndpointsArgs are the inputs of GeneratedAPI.WebhooksCreateEndpoints.
type WebhooksCreateEndpointsArgs struct {
	// URL is "url" in the body, required.
	URL string `json:"url"`

	// Events is "events" in the body.
	Events []string `json:"events,omitempty"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// WebhooksCreateEndpoints calls POST /api/v1/webhooks/endpoints: Register an endpoint.
func (a *GeneratedAPI) WebhooksCreateEndpoints(ctx context.Context, p *WebhooksCreateEndpointsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &WebhooksCreateEndpointsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.URL != "" {
		payload["url"] = p.URL
	}
	if p.Events != nil {
		payload["events"] = p.Events
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if _, ok := payload["url"]; !ok {
		return nil, apigenMissing("WebhooksCreateEndpoints", "URL")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/webhooks/endpoints", nil, payload)
}

// WebhooksDeleteEndpoints calls DELETE /api/v1/webhooks/endpoints/{id}: Delete an endpoint.
func (a *GeneratedAPI) WebhooksDeleteEndpoints(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/webhooks/endpoints/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// WebhooksEndpoints calls GET /api/v1/webhooks/endpoints: List endpoints.
func (a *GeneratedAPI) WebhooksEndpoints(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/webhooks/endpoints", nil, nil)
}

// WebhooksEventsArgs are the inputs of GeneratedAPI.WebhooksEvents.
type WebhooksEventsArgs struct {
	// Limit is "limit" in the query.
	Limit *int `query:"limit"`

	// Cursor is "cursor" in the query.
	Cursor *string `query:"cursor"`

	// Type is "type" in the query.
	Type *string `query:"type"`

	// Status is "status" in the query. One of: pending, sent, failed.
	Status *string `query:"status"`

	// EndpointID is "endpointId" in the query.
	EndpointID *string `query:"endpointId"`
}

// WebhooksEvents calls GET /api/v1/webhooks/events: List webhook deliveries.
func (a *GeneratedAPI) WebhooksEvents(ctx context.Context, p *WebhooksEventsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &WebhooksEventsArgs{}
	}
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(*p.Limit))
	}
	if p.Cursor != nil {
		q.Set("cursor", apigenQueryValue(*p.Cursor))
	}
	if p.Type != nil {
		q.Set("type", apigenQueryValue(*p.Type))
	}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(*p.Status))
	}
	if p.EndpointID != nil {
		q.Set("endpointId", apigenQueryValue(*p.EndpointID))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/webhooks/events", q, nil)
}

// WebhooksEventsRetry calls POST /api/v1/webhooks/events/{id}/retry: Retry a webhook delivery.
func (a *GeneratedAPI) WebhooksEventsRetry(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/webhooks/events/" + url.PathEscape(id) + "/retry"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// WebhooksGetEvents calls GET /api/v1/webhooks/events/{id}: Get a webhook delivery.
func (a *GeneratedAPI) WebhooksGetEvents(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/webhooks/events/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// WebhooksUpdateEndpointsArgs are the inputs of GeneratedAPI.WebhooksUpdateEndpoints.
type WebhooksUpdateEndpointsArgs struct {
	// URL is "url" in the body.
	URL *string `json:"url,omitempty"`

	// Events is "events" in the body.
	Events []string `json:"events,omitempty"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Active is "active" in the body.
	Active *bool `json:"active,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// WebhooksUpdateEndpoints calls PATCH /api/v1/webhooks/endpoints/{id}: Update an endpoint.
func (a *GeneratedAPI) WebhooksUpdateEndpoints(ctx context.Context, id string, p *WebhooksUpdateEndpointsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &WebhooksUpdateEndpointsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.URL != nil {
		payload["url"] = *p.URL
	}
	if p.Events != nil {
		payload["events"] = p.Events
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if p.Active != nil {
		payload["active"] = *p.Active
	}
	path := "/api/v1/webhooks/endpoints/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// ShippingShipments2 is the old name of ShippingGetShipments (GET /api/v1/shipping/shipments/{id}).
//
// Deprecated: use ShippingGetShipments.
func (a *GeneratedAPI) ShippingShipments2(ctx context.Context, id string) (json.RawMessage, error) {
	return a.ShippingGetShipments(ctx, id)
}

// WebhooksEvents2 is the old name of WebhooksGetEvents (GET /api/v1/webhooks/events/{id}).
//
// Deprecated: use WebhooksGetEvents.
func (a *GeneratedAPI) WebhooksEvents2(ctx context.Context, id string) (json.RawMessage, error) {
	return a.WebhooksGetEvents(ctx, id)
}

// apigenBody copies Body, so the fields set over it never change the caller's map.
func apigenBody(body map[string]any) map[string]any {
	out := make(map[string]any, len(body))
	for k, v := range body {
		out[k] = v
	}
	return out
}

// apigenQueryValue writes a query value the way the server reads it: strings as they are,
// numbers and booleans as JSON writes them, anything else as JSON.
func apigenQueryValue(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		return strconv.FormatBool(x)
	case int:
		return strconv.Itoa(x)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	}
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprint(v)
	}
	return string(b)
}

// apigenMissing is the error for a required body field that was neither set nor in Body.
func apigenMissing(method, field string) error {
	return fmt.Errorf("%s needs %s (or its key in Body)", method, field)
}
