// Generated by apigen cli from backend/openapi.json — do not edit by hand.
// Every feature route as `api <area> <action>`; the call goes through callRoute
// (cli/src/lib/apigen-call.ts), which uses this CLI's own sign-in and client, and bad
// input through failRoute (the CLI's own error output).
import { Command } from 'commander';
import { callRoute, failRoute } from '../lib/apigen-call.js';

type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json';
interface Field { name: string; kind: Kind; required: boolean; choices?: string[] }
interface Route { name: string; aliases?: string[]; method: string; path: string; summary: string; pathParams: string[]; query: Field[]; body: Field[] | null }

export const API_ROUTES: Array<{ area: string; routes: Route[] }> = [
 {
  "area": "addresses",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/addresses",
    "summary": "Create an address",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "customerId",
      "kind": "string",
      "required": true
     },
     {
      "name": "label",
      "kind": "string",
      "required": true
     },
     {
      "name": "contactName",
      "kind": "string",
      "required": true
     },
     {
      "name": "contactPhone",
      "kind": "string",
      "required": true
     },
     {
      "name": "email",
      "kind": "string",
      "required": false
     },
     {
      "name": "address",
      "kind": "string",
      "required": true
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     },
     {
      "name": "postalCode",
      "kind": "string",
      "required": false
     },
     {
      "name": "areaId",
      "kind": "string",
      "required": false
     },
     {
      "name": "lat",
      "kind": "number",
      "required": false
     },
     {
      "name": "lng",
      "kind": "number",
      "required": false
     },
     {
      "name": "isDefault",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/addresses/{id}",
    "summary": "Delete an address",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/addresses",
    "summary": "List addresses",
    "pathParams": [],
    "query": [
     {
      "name": "customer_id",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/addresses/{id}",
    "summary": "Update an address",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "label",
      "kind": "string",
      "required": false
     },
     {
      "name": "contactName",
      "kind": "string",
      "required": false
     },
     {
      "name": "contactPhone",
      "kind": "string",
      "required": false
     },
     {
      "name": "email",
      "kind": "string",
      "required": false
     },
     {
      "name": "address",
      "kind": "string",
      "required": false
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     },
     {
      "name": "postalCode",
      "kind": "string",
      "required": false
     },
     {
      "name": "areaId",
      "kind": "string",
      "required": false
     },
     {
      "name": "lat",
      "kind": "number",
      "required": false
     },
     {
      "name": "lng",
      "kind": "number",
      "required": false
     },
     {
      "name": "isDefault",
      "kind": "boolean",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "api-keys",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/api-keys",
    "summary": "Create an api key",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "scopes",
      "kind": "array",
      "required": false
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/api-keys",
    "summary": "List api keys",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "revoke",
    "method": "POST",
    "path": "/api/v1/api-keys/{id}/revoke",
    "summary": "Revoke an api key",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "audit-log",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/audit-log",
    "summary": "List audit log",
    "pathParams": [],
    "query": [
     {
      "name": "action",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     },
     {
      "name": "target_type",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "billing",
  "routes": [
   {
    "name": "cancel",
    "method": "POST",
    "path": "/api/v1/billing/cancel",
    "summary": "Create a cancel",
    "pathParams": [],
    "query": [],
    "body": []
   },
   {
    "name": "checkout",
    "method": "POST",
    "path": "/api/v1/billing/checkout",
    "summary": "Create a checkout",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "plan",
      "kind": "string",
      "required": true,
      "choices": [
       "STARTER",
       "GROWTH",
       "SCALE"
      ]
     },
     {
      "name": "email",
      "kind": "string",
      "required": false
     },
     {
      "name": "name",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "invoices",
    "method": "GET",
    "path": "/api/v1/billing/invoices",
    "summary": "List invoices",
    "pathParams": [],
    "query": [
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "plan",
    "method": "GET",
    "path": "/api/v1/billing/plan",
    "summary": "List plan",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "plans",
    "method": "GET",
    "path": "/api/v1/billing/plans",
    "summary": "Public, no auth.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "subscription",
    "method": "GET",
    "path": "/api/v1/billing/subscription",
    "summary": "List subscription",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "usage",
    "method": "GET",
    "path": "/api/v1/billing/usage",
    "summary": "List usage",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "deliveries",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/deliveries",
    "summary": "Create a delivery",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "productId",
      "kind": "string",
      "required": true
     },
     {
      "name": "customerId",
      "kind": "string",
      "required": true
     },
     {
      "name": "checkoutSessionId",
      "kind": "string",
      "required": true
     },
     {
      "name": "maxDownloads",
      "kind": "number",
      "required": false
     },
     {
      "name": "expiresAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "externalSource",
      "kind": "string",
      "required": false
     },
     {
      "name": "externalRef",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "download",
    "method": "POST",
    "path": "/api/v1/deliveries/{id}/download",
    "summary": "Record a download.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "extend",
    "method": "POST",
    "path": "/api/v1/deliveries/{id}/extend",
    "summary": "Extend the download window 30 days (from now, or the current expiry).",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/deliveries/{id}",
    "summary": "Get a delivery",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/deliveries",
    "summary": "List deliveries",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "reset-downloads",
    "method": "POST",
    "path": "/api/v1/deliveries/{id}/reset-downloads",
    "summary": "Reset the download counter so the buyer can download again.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "revoke",
    "method": "POST",
    "path": "/api/v1/deliveries/{id}/revoke",
    "summary": "Revoke: expire the delivery now.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "integrations",
  "routes": [
   {
    "name": "status",
    "method": "GET",
    "path": "/api/v1/integrations/status",
    "summary": "List status",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "licenses",
  "routes": [
   {
    "name": "activate",
    "method": "POST",
    "path": "/api/v1/licenses/activate",
    "summary": "/v1/licenses/activate is unauthenticated — buyers' apps call this with the license key directly.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "key",
      "kind": "string",
      "required": true
     },
     {
      "name": "instanceId",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/licenses",
    "summary": "Create a license",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "productId",
      "kind": "string",
      "required": true
     },
     {
      "name": "customerId",
      "kind": "string",
      "required": true
     },
     {
      "name": "maxActivations",
      "kind": "number",
      "required": false
     },
     {
      "name": "expiresAt",
      "kind": "string",
      "required": false
     },
     {
      "name": "externalSource",
      "kind": "string",
      "required": false
     },
     {
      "name": "externalRef",
      "kind": "string",
      "required": false
     },
     {
      "name": "key",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "deactivate",
    "method": "POST",
    "path": "/api/v1/licenses/deactivate",
    "summary": "Release a previously-activated instance.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "key",
      "kind": "string",
      "required": true
     },
     {
      "name": "instanceId",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/licenses",
    "summary": "List licenses",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "lookup",
    "method": "GET",
    "path": "/api/v1/licenses/lookup",
    "summary": "Full license + its activation rows, resolved by key within the merchant's account.",
    "pathParams": [],
    "query": [
     {
      "name": "key",
      "kind": "string",
      "required": true
     }
    ],
    "body": null
   },
   {
    "name": "revoke",
    "method": "POST",
    "path": "/api/v1/licenses/{id}/revoke",
    "summary": "Revoke a license",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "validate",
    "method": "GET",
    "path": "/api/v1/licenses/validate",
    "summary": "Public unauthenticated endpoints — buyers' software calls these with just the license key.",
    "pathParams": [],
    "query": [
     {
      "name": "key",
      "kind": "string",
      "required": true
     },
     {
      "name": "productId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "products",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/products",
    "summary": "Create a product",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "sku",
      "kind": "string",
      "required": false
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "type",
      "kind": "string",
      "required": false,
      "choices": [
       "physical",
       "digital",
       "license"
      ]
     },
     {
      "name": "weight",
      "kind": "number",
      "required": false
     },
     {
      "name": "length",
      "kind": "number",
      "required": false
     },
     {
      "name": "width",
      "kind": "number",
      "required": false
     },
     {
      "name": "height",
      "kind": "number",
      "required": false
     },
     {
      "name": "licenseEnabled",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "maxActivations",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "create-variants",
    "method": "POST",
    "path": "/api/v1/products/{id}/variants",
    "summary": "Variants a product",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "sku",
      "kind": "string",
      "required": false
     },
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "priceCents",
      "kind": "number",
      "required": false
     },
     {
      "name": "costCents",
      "kind": "number",
      "required": false
     },
     {
      "name": "lowStockThreshold",
      "kind": "number",
      "required": false
     },
     {
      "name": "weight",
      "kind": "number",
      "required": false
     },
     {
      "name": "isDefault",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/products/{id}",
    "summary": "Delete a product",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-variants",
    "method": "DELETE",
    "path": "/api/v1/products/{id}/variants/{variantId}",
    "summary": "Delete a variant",
    "pathParams": [
     "id",
     "variantId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/products/{id}",
    "summary": "Get a product",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/products",
    "summary": "List products",
    "pathParams": [],
    "query": [
     {
      "name": "archived",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/products/{id}",
    "summary": "Update a product",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "sku",
      "kind": "string",
      "required": false
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "type",
      "kind": "string",
      "required": false,
      "choices": [
       "physical",
       "digital",
       "license"
      ]
     },
     {
      "name": "weight",
      "kind": "number",
      "required": false
     },
     {
      "name": "length",
      "kind": "number",
      "required": false
     },
     {
      "name": "width",
      "kind": "number",
      "required": false
     },
     {
      "name": "height",
      "kind": "number",
      "required": false
     },
     {
      "name": "licenseEnabled",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "maxActivations",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "update-variants",
    "method": "PATCH",
    "path": "/api/v1/products/{id}/variants/{variantId}",
    "summary": "Update a variant",
    "pathParams": [
     "id",
     "variantId"
    ],
    "query": [],
    "body": [
     {
      "name": "sku",
      "kind": "string",
      "required": false
     },
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "priceCents",
      "kind": "number",
      "required": false
     },
     {
      "name": "costCents",
      "kind": "number",
      "required": false
     },
     {
      "name": "lowStockThreshold",
      "kind": "number",
      "required": false
     },
     {
      "name": "weight",
      "kind": "number",
      "required": false
     },
     {
      "name": "isDefault",
      "kind": "boolean",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "shipments",
  "routes": [
   {
    "name": "cancel",
    "method": "POST",
    "path": "/api/v1/shipments/{id}/cancel",
    "summary": "Cancel a booking the courier hasn't collected yet, and give back the shipping credit confirm-pickup consumed.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "reason",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "confirm-pickup",
    "method": "POST",
    "path": "/api/v1/shipments/{id}/confirm-pickup",
    "summary": "F-004: Merchant clicks \"Book courier\" once the parcel is actually ready.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/shipments",
    "summary": "Create a shipment",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "productId",
      "kind": "string",
      "required": false
     },
     {
      "name": "checkoutSessionId",
      "kind": "string",
      "required": false
     },
     {
      "name": "customerId",
      "kind": "string",
      "required": false
     },
     {
      "name": "customerEmail",
      "kind": "string",
      "required": false
     },
     {
      "name": "courierCode",
      "kind": "string",
      "required": true
     },
     {
      "name": "courierServiceCode",
      "kind": "string",
      "required": true
     },
     {
      "name": "courierType",
      "kind": "string",
      "required": true
     },
     {
      "name": "price",
      "kind": "number",
      "required": true
     },
     {
      "name": "insurance",
      "kind": "number",
      "required": false
     },
     {
      "name": "insured",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "origin",
      "kind": "json",
      "required": true
     },
     {
      "name": "destination",
      "kind": "json",
      "required": true
     },
     {
      "name": "items",
      "kind": "array",
      "required": true
     },
     {
      "name": "externalSource",
      "kind": "string",
      "required": false
     },
     {
      "name": "externalRef",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/shipments/{id}",
    "summary": "Get a shipment",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "label",
    "method": "GET",
    "path": "/api/v1/shipments/{id}/label",
    "summary": "Biteship deliberately has no shipping-label API.",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "size",
      "kind": "string",
      "required": false,
      "choices": [
       "a4",
       "thermal-80x100",
       "thermal-100x150"
      ]
     },
     {
      "name": "showSenderPhone",
      "kind": "string",
      "required": false,
      "choices": [
       "true",
       "false"
      ]
     },
     {
      "name": "showRecipientPhone",
      "kind": "string",
      "required": false,
      "choices": [
       "true",
       "false"
      ]
     },
     {
      "name": "maskRecipientName",
      "kind": "string",
      "required": false,
      "choices": [
       "true",
       "false"
      ]
     },
     {
      "name": "maskRecipientPhone",
      "kind": "string",
      "required": false,
      "choices": [
       "true",
       "false"
      ]
     },
     {
      "name": "showShippingCost",
      "kind": "string",
      "required": false,
      "choices": [
       "true",
       "false"
      ]
     },
     {
      "name": "showInsurance",
      "kind": "string",
      "required": false,
      "choices": [
       "true",
       "false"
      ]
     },
     {
      "name": "showItems",
      "kind": "string",
      "required": false,
      "choices": [
       "true",
       "false"
      ]
     },
     {
      "name": "showItemDescriptions",
      "kind": "string",
      "required": false,
      "choices": [
       "true",
       "false"
      ]
     },
     {
      "name": "showItemSkus",
      "kind": "string",
      "required": false,
      "choices": [
       "true",
       "false"
      ]
     }
    ],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/shipments",
    "summary": "List shipments",
    "pathParams": [],
    "query": [
     {
      "name": "status",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "rebook",
    "method": "POST",
    "path": "/api/v1/shipments/{id}/rebook",
    "summary": "Rebook a shipment",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "courierCode",
      "kind": "string",
      "required": false
     },
     {
      "name": "courierServiceCode",
      "kind": "string",
      "required": false
     },
     {
      "name": "courierType",
      "kind": "string",
      "required": false
     },
     {
      "name": "price",
      "kind": "number",
      "required": false
     },
     {
      "name": "insured",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "insurance",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "tracking",
    "method": "GET",
    "path": "/api/v1/shipments/{id}/tracking",
    "summary": "F-008: live tracking detail (driver, status history, ETA) from Biteship.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "shipping",
  "routes": [
   {
    "name": "areas",
    "method": "GET",
    "path": "/api/v1/shipping/areas",
    "summary": "List areas",
    "pathParams": [],
    "query": [
     {
      "name": "q",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "config",
    "method": "GET",
    "path": "/api/v1/shipping/config",
    "summary": "List config",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "couriers",
    "method": "GET",
    "path": "/api/v1/shipping/couriers",
    "summary": "In Fulkruma we still gate this behind requireAuth: the dashboard always has a session, and we want per-merchant API key resolution.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "get-shipments",
    "method": "GET",
    "path": "/api/v1/shipping/shipments/{id}",
    "summary": "Get a shipment",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "shipments-2"
    ]
   },
   {
    "name": "origin",
    "method": "GET",
    "path": "/api/v1/shipping/origin",
    "summary": "List origin",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "rates",
    "method": "POST",
    "path": "/api/v1/shipping/rates",
    "summary": "Create a rate",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "destination",
      "kind": "json",
      "required": true
     },
     {
      "name": "items",
      "kind": "array",
      "required": true
     },
     {
      "name": "insurance",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "set-config",
    "method": "PUT",
    "path": "/api/v1/shipping/config",
    "summary": "Set config",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "apiKey",
      "kind": "string",
      "required": false
     },
     {
      "name": "defaultOriginId",
      "kind": "string",
      "required": false
     },
     {
      "name": "enabledCouriers",
      "kind": "array",
      "required": false
     },
     {
      "name": "defaultCourier",
      "kind": "string",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "shipments",
    "method": "GET",
    "path": "/api/v1/shipping/shipments",
    "summary": "List shipments",
    "pathParams": [],
    "query": [
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "shipments-cancel",
    "method": "POST",
    "path": "/api/v1/shipping/shipments/{id}/cancel",
    "summary": "Legacy namespace.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "reason",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "shipments-label",
    "method": "GET",
    "path": "/api/v1/shipping/shipments/{id}/label",
    "summary": "Legacy shipping namespace.",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "size",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "shipments-rebook",
    "method": "POST",
    "path": "/api/v1/shipping/shipments/{id}/rebook",
    "summary": "Legacy-namespace twin of /shipments/:id/rebook.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "courierCode",
      "kind": "string",
      "required": false
     },
     {
      "name": "courierServiceCode",
      "kind": "string",
      "required": false
     },
     {
      "name": "courierType",
      "kind": "string",
      "required": false
     },
     {
      "name": "price",
      "kind": "number",
      "required": false
     },
     {
      "name": "insured",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "insurance",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "track",
    "method": "GET",
    "path": "/api/v1/shipping/track/{waybillId}",
    "summary": "Get a track",
    "pathParams": [
     "waybillId"
    ],
    "query": [
     {
      "name": "courier",
      "kind": "string",
      "required": true
     }
    ],
    "body": null
   },
   {
    "name": "update-origin",
    "method": "PATCH",
    "path": "/api/v1/shipping/origin",
    "summary": "Update origin",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "address",
      "kind": "string",
      "required": true
     },
     {
      "name": "province",
      "kind": "string",
      "required": false
     },
     {
      "name": "city",
      "kind": "string",
      "required": false
     },
     {
      "name": "district",
      "kind": "string",
      "required": false
     },
     {
      "name": "village",
      "kind": "string",
      "required": false
     },
     {
      "name": "postal",
      "kind": "string",
      "required": false
     },
     {
      "name": "areaId",
      "kind": "string",
      "required": false
     },
     {
      "name": "lat",
      "kind": "number",
      "required": false
     },
     {
      "name": "lng",
      "kind": "number",
      "required": false
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     },
     {
      "name": "contactName",
      "kind": "string",
      "required": true
     },
     {
      "name": "contactPhone",
      "kind": "string",
      "required": true
     },
     {
      "name": "couriers",
      "kind": "array",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "shipping-credits",
  "routes": [
   {
    "name": "adjust",
    "method": "POST",
    "path": "/api/v1/shipping-credits/adjust",
    "summary": "Create an adjust",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "amount",
      "kind": "number",
      "required": true
     },
     {
      "name": "kind",
      "kind": "string",
      "required": true,
      "choices": [
       "manual_adjustment",
       "shipment_refund"
      ]
     },
     {
      "name": "shipmentId",
      "kind": "string",
      "required": false
     },
     {
      "name": "externalRef",
      "kind": "string",
      "required": false
     },
     {
      "name": "memo",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "checkout",
    "method": "POST",
    "path": "/api/v1/shipping-credits/checkout",
    "summary": "Create a checkout",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "amount",
      "kind": "number",
      "required": true
     },
     {
      "name": "email",
      "kind": "string",
      "required": false
     },
     {
      "name": "name",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/shipping-credits",
    "summary": "Balance for the calling merchant.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "topup",
    "method": "POST",
    "path": "/api/v1/shipping-credits/topup",
    "summary": "Create a topup",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "amount",
      "kind": "number",
      "required": true
     },
     {
      "name": "externalRef",
      "kind": "string",
      "required": false
     },
     {
      "name": "memo",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "transactions",
    "method": "GET",
    "path": "/api/v1/shipping-credits/transactions",
    "summary": "List transactions",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "stats",
  "routes": [
   {
    "name": "overview",
    "method": "GET",
    "path": "/api/v1/stats/overview",
    "summary": "Powers the /dashboard overview tiles.",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "stock",
  "routes": [
   {
    "name": "adjust",
    "method": "POST",
    "path": "/api/v1/stock/adjust",
    "summary": "Create an adjust",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "variantId",
      "kind": "string",
      "required": true
     },
     {
      "name": "warehouseId",
      "kind": "string",
      "required": true
     },
     {
      "name": "delta",
      "kind": "number",
      "required": true
     },
     {
      "name": "reason",
      "kind": "string",
      "required": true,
      "choices": [
       "manual_adjust",
       "initial_stock",
       "transfer_in",
       "transfer_out",
       "damaged",
       "returned_to_supplier",
       "refund_restock",
       "import"
      ]
     },
     {
      "name": "note",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "levels",
    "method": "GET",
    "path": "/api/v1/stock/levels",
    "summary": "List levels",
    "pathParams": [],
    "query": [
     {
      "name": "variant_id",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "movements",
    "method": "GET",
    "path": "/api/v1/stock/movements",
    "summary": "List movements",
    "pathParams": [],
    "query": [
     {
      "name": "variant_id",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "reservations",
    "method": "GET",
    "path": "/api/v1/stock/reservations",
    "summary": "List reservations",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "warehouses",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/warehouses",
    "summary": "Create a warehouse",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "address",
      "kind": "string",
      "required": false
     },
     {
      "name": "city",
      "kind": "string",
      "required": false
     },
     {
      "name": "postal",
      "kind": "string",
      "required": false
     },
     {
      "name": "lat",
      "kind": "number",
      "required": false
     },
     {
      "name": "lng",
      "kind": "number",
      "required": false
     },
     {
      "name": "phone",
      "kind": "string",
      "required": false
     },
     {
      "name": "isDefault",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/warehouses/{id}",
    "summary": "Delete a warehouse",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/warehouses",
    "summary": "List warehouses",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/warehouses/{id}",
    "summary": "Update a warehouse",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "address",
      "kind": "string",
      "required": false
     },
     {
      "name": "city",
      "kind": "string",
      "required": false
     },
     {
      "name": "postal",
      "kind": "string",
      "required": false
     },
     {
      "name": "lat",
      "kind": "number",
      "required": false
     },
     {
      "name": "lng",
      "kind": "number",
      "required": false
     },
     {
      "name": "phone",
      "kind": "string",
      "required": false
     },
     {
      "name": "isDefault",
      "kind": "boolean",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "webhooks",
  "routes": [
   {
    "name": "create-endpoints",
    "method": "POST",
    "path": "/api/v1/webhooks/endpoints",
    "summary": "Register an endpoint.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": true
     },
     {
      "name": "events",
      "kind": "array",
      "required": false
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete-endpoints",
    "method": "DELETE",
    "path": "/api/v1/webhooks/endpoints/{id}",
    "summary": "Delete an endpoint",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "endpoints",
    "method": "GET",
    "path": "/api/v1/webhooks/endpoints",
    "summary": "List endpoints",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "events",
    "method": "GET",
    "path": "/api/v1/webhooks/events",
    "summary": "List webhook deliveries.",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "type",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "pending",
       "sent",
       "failed"
      ]
     },
     {
      "name": "endpointId",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "events-retry",
    "method": "POST",
    "path": "/api/v1/webhooks/events/{id}/retry",
    "summary": "Retry a webhook delivery.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get-events",
    "method": "GET",
    "path": "/api/v1/webhooks/events/{id}",
    "summary": "Get a webhook delivery.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "events-2"
    ]
   },
   {
    "name": "update-endpoints",
    "method": "PATCH",
    "path": "/api/v1/webhooks/endpoints/{id}",
    "summary": "Update an endpoint.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": false
     },
     {
      "name": "events",
      "kind": "array",
      "required": false
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     }
    ]
   }
  ]
 }
];

// A field whose flag would clash with this command's own options or the CLI's global ones
// is given as --field-<name>.
const RESERVED = new Set(['help', 'version', 'json', 'profile', 'api', 'on-behalf-of', 'color', 'no-color', 'body-json']);
const plain = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
const flag = (name: string): string => (RESERVED.has(plain(name)) ? `field-${plain(name)}` : plain(name));
const camel = (name: string): string => flag(name).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function value(field: Field, raw: string): unknown {
  if (field.kind === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(`--${flag(field.name)} must be a number`);
    return n;
  }
  if (field.kind === 'boolean') return raw === '' || raw === 'true' || raw === '1' || raw === 'yes';
  if (field.kind === 'array') return raw.trim().startsWith('[') ? JSON.parse(raw) : raw.split(',').map((x) => x.trim()).filter(Boolean);
  if (field.kind === 'json') return JSON.parse(raw);
  if (field.choices && !field.choices.includes(raw)) throw new Error(`--${flag(field.name)} must be one of: ${field.choices.join(', ')}`);
  return raw;
}

export function buildApiCommand(): Command {
  const api = new Command('api').description('Every route of the API, one command each (generated from the API spec)');
  for (const { area, routes } of API_ROUTES) {
    const group = new Command(area).description(`${area} routes`);
    for (const route of routes) {
      for (const name of [route.name, ...(route.aliases ?? [])]) {
      const cmd = new Command(name).description(`${route.summary} (${route.method} ${route.path})`);
      for (const p of route.pathParams) cmd.argument(`<${p}>`);
      const fields = [...route.query, ...(route.body ?? [])];
      for (const f of fields) {
        const hint = f.choices ? ` (${f.choices.join('|')})` : f.kind === 'json' || f.kind === 'array' ? ` (${f.kind})` : '';
        cmd.option(f.kind === 'boolean' ? `--${flag(f.name)} [value]` : `--${flag(f.name)} <value>`, `${f.required ? 'required' : 'optional'}${hint}`);
      }
      if (route.body) cmd.option('--body-json <json>', 'the whole body as JSON (fields given as flags override it)');
      cmd.action(async (...parts: unknown[]) => {
        const command = parts[parts.length - 1] as Command;
        const opts = command.opts() as Record<string, string | boolean | undefined>;
        try {
        let path = route.path;
        route.pathParams.forEach((p, i) => { path = path.replace(`{${p}}`, encodeURIComponent(String(parts[i]))); });
        const query: Record<string, unknown> = {};
        for (const f of route.query) {
          const raw = opts[camel(f.name)];
          if (raw !== undefined) query[f.name] = value(f, raw === true ? '' : String(raw));
        }
        let body: Record<string, unknown> | undefined;
        if (route.body) {
          body = opts.bodyJson ? (JSON.parse(String(opts.bodyJson)) as Record<string, unknown>) : {};
          for (const f of route.body) {
            const raw = opts[camel(f.name)];
            if (raw !== undefined) body[f.name] = value(f, raw === true ? '' : String(raw));
          }
          const missing = route.body.filter((f) => f.required && body![f.name] === undefined).map((f) => `--${flag(f.name)}`);
          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);
        }
        await callRoute(command, route.method, path, query, body);
        } catch (err) {
          await failRoute(command, err);
        }
      });
      group.addCommand(cmd, { hidden: name !== route.name });
      }
    }
    api.addCommand(group);
  }
  return api;
}
