// Generated by apigen docs from backend/openapi.json — do not edit by hand.
import type { DocMeta } from './markdown';

export const REFERENCE_NAV: DocMeta[] = [
  {
    "slug": "api/reference",
    "title": "All routes",
    "group": "API reference (every route)",
    "href": "/docs/api/reference"
  },
  {
    "slug": "api/reference/addresses",
    "title": "Addresses",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/addresses"
  },
  {
    "slug": "api/reference/api-keys",
    "title": "Api keys",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/api-keys"
  },
  {
    "slug": "api/reference/audit-log",
    "title": "Audit log",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/audit-log"
  },
  {
    "slug": "api/reference/billing",
    "title": "Billing",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/billing"
  },
  {
    "slug": "api/reference/deliveries",
    "title": "Deliveries",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/deliveries"
  },
  {
    "slug": "api/reference/licenses",
    "title": "Licenses",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/licenses"
  },
  {
    "slug": "api/reference/products",
    "title": "Products",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/products"
  },
  {
    "slug": "api/reference/shipments",
    "title": "Shipments",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/shipments"
  },
  {
    "slug": "api/reference/shipping",
    "title": "Shipping",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/shipping"
  },
  {
    "slug": "api/reference/shipping-credits",
    "title": "Shipping credits",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/shipping-credits"
  },
  {
    "slug": "api/reference/stats",
    "title": "Stats",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/stats"
  },
  {
    "slug": "api/reference/stock",
    "title": "Stock",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/stock"
  },
  {
    "slug": "api/reference/warehouses",
    "title": "Warehouses",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/warehouses"
  },
  {
    "slug": "api/reference/webhooks",
    "title": "Webhooks",
    "group": "API reference (every route)",
    "href": "/docs/api/reference/webhooks"
  }
];
