// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build/dev via the prebuild/predev npm hooks.
// Safe to commit (placeholder values); the real values come from git at build.
export const APP_VERSION = "d47adb6-dirty";
export const BUILD_SHA = "d47adb6";
export const BUILD_DATE = "2026-08-15T05:51:20.160Z";
