// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build/dev via the prebuild/predev npm hooks.
// Safe to commit (placeholder values); the real values come from git at build.
export const APP_VERSION = "7fef494-dirty";
export const BUILD_SHA = "7fef494";
export const BUILD_DATE = "2026-06-29T15:11:16.390Z";
