// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT BY HAND.
// Regenerated on every build/dev via the prebuild/predev npm hooks.
// Safe to commit (placeholder values); the real values come from git at build.
export const APP_VERSION = "sdk/go/v0.1.0-113-g5e4efba-dirty";
export const BUILD_SHA = "5e4efba";
export const BUILD_DATE = "2026-06-29T14:31:31.830Z";
