// Every Fulkruma feature route, one method each — generated by apigen from
// backend/openapi.json. Do not edit by hand; regenerate after the API changes.
// Reach them as `client.api.<area><Action>(...)`; each call goes through the client's
// own `apigenRequest` (its sign-in and response envelope).

export interface ApigenTransport {
  apigenRequest(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<unknown>;
}

/** All 79 feature routes of the Fulkruma API. */
export class GeneratedApi {
  constructor(private readonly client: ApigenTransport) {}

  private call(method: string, path: string, query: Record<string, unknown>, body: unknown): Promise<unknown> {
    const q = Object.fromEntries(Object.entries(query).filter(([, v]) => v !== undefined && v !== null));
    return this.client.apigenRequest(method, path, Object.keys(q).length ? q : undefined, body);
  }

  /** Create an address (POST /api/v1/addresses) */
  addressesCreate(input: { "customerId": string; "label": string; "contactName": string; "contactPhone": string; "email"?: string; "address": string; "note"?: string; "postalCode"?: string; "areaId"?: string; "lat"?: number; "lng"?: number; "isDefault"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/addresses`, query, all);
  }

  /** Delete an address (DELETE /api/v1/addresses/{id}) */
  addressesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/addresses/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List addresses (GET /api/v1/addresses) */
  addressesList(input?: { "customer_id"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["customer_id"] = all["customer_id"]; delete all["customer_id"];
    return this.call("GET", `/api/v1/addresses`, query, undefined);
  }

  /** Update an address (PATCH /api/v1/addresses/{id}) */
  addressesUpdate(id: string, input?: { "label"?: string; "contactName"?: string; "contactPhone"?: string; "email"?: string; "address"?: string; "note"?: string; "postalCode"?: string; "areaId"?: string; "lat"?: number; "lng"?: number; "isDefault"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/addresses/${encodeURIComponent(id)}`, query, all);
  }

  /** Create an api key (POST /api/v1/api-keys) */
  apiKeysCreate(input: { "name": string; "scopes"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/api-keys`, query, all);
  }

  /** List api keys (GET /api/v1/api-keys) */
  apiKeysList(): Promise<unknown> {
    return this.call("GET", `/api/v1/api-keys`, {}, undefined);
  }

  /** Revoke an api key (POST /api/v1/api-keys/{id}/revoke) */
  apiKeysRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/api-keys/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** List audit log (GET /api/v1/audit-log) */
  auditLogList(input?: { "action"?: unknown; "limit"?: unknown; "target_type"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["action"] = all["action"]; delete all["action"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["target_type"] = all["target_type"]; delete all["target_type"];
    return this.call("GET", `/api/v1/audit-log`, query, undefined);
  }

  /** Create a cancel (POST /api/v1/billing/cancel) */
  billingCancel(input?: { [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/cancel`, query, all);
  }

  /** Create a checkout (POST /api/v1/billing/checkout) */
  billingCheckout(input: { "plan": "STARTER" | "GROWTH" | "SCALE"; "email"?: string; "name"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/billing/checkout`, query, all);
  }

  /** List invoices (GET /api/v1/billing/invoices) */
  billingInvoices(input?: { "cursor"?: unknown; "limit"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    return this.call("GET", `/api/v1/billing/invoices`, query, undefined);
  }

  /** List plan (GET /api/v1/billing/plan) */
  billingPlan(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/plan`, {}, undefined);
  }

  /** Public, no auth. (GET /api/v1/billing/plans) */
  billingPlans(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/plans`, {}, undefined);
  }

  /** List subscription (GET /api/v1/billing/subscription) */
  billingSubscription(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/subscription`, {}, undefined);
  }

  /** List usage (GET /api/v1/billing/usage) */
  billingUsage(): Promise<unknown> {
    return this.call("GET", `/api/v1/billing/usage`, {}, undefined);
  }

  /** Create a delivery (POST /api/v1/deliveries) */
  deliveriesCreate(input: { "productId": string; "customerId": string; "checkoutSessionId": string; "maxDownloads"?: number; "expiresAt"?: string; "externalSource"?: string; "externalRef"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/deliveries`, query, all);
  }

  /** Extend the download window 30 days (from now, or the current expiry). (POST /api/v1/deliveries/{id}/extend) */
  deliveriesExtend(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/deliveries/${encodeURIComponent(id)}/extend`, {}, undefined);
  }

  /** Get a delivery (GET /api/v1/deliveries/{id}) */
  deliveriesGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/deliveries/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List deliveries (GET /api/v1/deliveries) */
  deliveriesList(): Promise<unknown> {
    return this.call("GET", `/api/v1/deliveries`, {}, undefined);
  }

  /** Reset the download counter so the buyer can download again. (POST /api/v1/deliveries/{id}/reset-downloads) */
  deliveriesResetDownloads(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/deliveries/${encodeURIComponent(id)}/reset-downloads`, {}, undefined);
  }

  /** Revoke: expire the delivery now. (POST /api/v1/deliveries/{id}/revoke) */
  deliveriesRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/deliveries/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** List status (GET /api/v1/integrations/status) */
  integrationsStatus(): Promise<unknown> {
    return this.call("GET", `/api/v1/integrations/status`, {}, undefined);
  }

  /** /v1/licenses/activate is unauthenticated — buyers' apps call this with the license key directly. (POST /api/v1/licenses/activate) */
  licensesActivate(input: { "key": string; "instanceId": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/licenses/activate`, query, all);
  }

  /** Create a license (POST /api/v1/licenses) */
  licensesCreate(input: { "productId": string; "customerId": string; "maxActivations"?: number; "expiresAt"?: string; "externalSource"?: string; "externalRef"?: string; "key"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/licenses`, query, all);
  }

  /** Release a previously-activated instance. (POST /api/v1/licenses/deactivate) */
  licensesDeactivate(input: { "key": string; "instanceId": string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/licenses/deactivate`, query, all);
  }

  /** List licenses (GET /api/v1/licenses) */
  licensesList(): Promise<unknown> {
    return this.call("GET", `/api/v1/licenses`, {}, undefined);
  }

  /** Full license + its activation rows, resolved by key within the merchant's account. (GET /api/v1/licenses/lookup) */
  licensesLookup(input: { "key": string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["key"] = all["key"]; delete all["key"];
    return this.call("GET", `/api/v1/licenses/lookup`, query, undefined);
  }

  /** Revoke a license (POST /api/v1/licenses/{id}/revoke) */
  licensesRevoke(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/licenses/${encodeURIComponent(id)}/revoke`, {}, undefined);
  }

  /** Public unauthenticated endpoints — buyers' software calls these with just the license key. (GET /api/v1/licenses/validate) */
  licensesValidate(input: { "key": string; "productId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["key"] = all["key"]; delete all["key"];
    query["productId"] = all["productId"]; delete all["productId"];
    return this.call("GET", `/api/v1/licenses/validate`, query, undefined);
  }

  /** Create a product (POST /api/v1/products) */
  productsCreate(input: { "name": string; "sku"?: string; "description"?: string; "type"?: "physical" | "digital" | "license"; "weight"?: number; "length"?: number; "width"?: number; "height"?: number; "licenseEnabled"?: boolean; "maxActivations"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/products`, query, all);
  }

  /** Variants a product (POST /api/v1/products/{id}/variants) */
  productsCreateVariants(id: string, input: { "sku"?: string; "name": string; "priceCents"?: number; "costCents"?: number; "lowStockThreshold"?: number; "weight"?: number; "isDefault"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/products/${encodeURIComponent(id)}/variants`, query, all);
  }

  /** Delete a product (DELETE /api/v1/products/{id}) */
  productsDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/products/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Delete a variant (DELETE /api/v1/products/{id}/variants/{variantId}) */
  productsDeleteVariants(id: string, variantId: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/products/${encodeURIComponent(id)}/variants/${encodeURIComponent(variantId)}`, {}, undefined);
  }

  /** Get a product (GET /api/v1/products/{id}) */
  productsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/products/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List products (GET /api/v1/products) */
  productsList(input?: { "archived"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["archived"] = all["archived"]; delete all["archived"];
    return this.call("GET", `/api/v1/products`, query, undefined);
  }

  /** Update a product (PATCH /api/v1/products/{id}) */
  productsUpdate(id: string, input?: { "name"?: string; "sku"?: string; "description"?: string; "type"?: "physical" | "digital" | "license"; "weight"?: number; "length"?: number; "width"?: number; "height"?: number; "licenseEnabled"?: boolean; "maxActivations"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/products/${encodeURIComponent(id)}`, query, all);
  }

  /** Update a variant (PATCH /api/v1/products/{id}/variants/{variantId}) */
  productsUpdateVariants(id: string, variantId: string, input?: { "sku"?: string; "name"?: string; "priceCents"?: number; "costCents"?: number; "lowStockThreshold"?: number; "weight"?: number; "isDefault"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/products/${encodeURIComponent(id)}/variants/${encodeURIComponent(variantId)}`, query, all);
  }

  /** Cancel a booking the courier hasn't collected yet, and give back the shipping credit confirm-pickup consumed. (POST /api/v1/shipments/{id}/cancel) */
  shipmentsCancel(id: string, input?: { "reason"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shipments/${encodeURIComponent(id)}/cancel`, query, all);
  }

  /** F-004: Merchant clicks "Book courier" once the parcel is actually ready. (POST /api/v1/shipments/{id}/confirm-pickup) */
  shipmentsConfirmPickup(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/shipments/${encodeURIComponent(id)}/confirm-pickup`, {}, undefined);
  }

  /** Create a shipment (POST /api/v1/shipments) */
  shipmentsCreate(input: { "productId"?: string; "checkoutSessionId"?: string; "customerId"?: string; "customerEmail"?: string; "courierCode": string; "courierServiceCode": string; "courierType": string; "price": number; "insurance"?: number; "insured"?: boolean; "origin": Record<string, unknown>; "destination": Record<string, unknown>; "items": unknown[]; "externalSource"?: string; "externalRef"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shipments`, query, all);
  }

  /** Get a shipment (GET /api/v1/shipments/{id}) */
  shipmentsGet(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/shipments/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Biteship deliberately has no shipping-label API. (GET /api/v1/shipments/{id}/label) */
  shipmentsLabel(id: string, input?: { "size"?: "a4" | "thermal-80x100" | "thermal-100x150"; "showSenderPhone"?: "true" | "false"; "showRecipientPhone"?: "true" | "false"; "maskRecipientName"?: "true" | "false"; "maskRecipientPhone"?: "true" | "false"; "showShippingCost"?: "true" | "false"; "showInsurance"?: "true" | "false"; "showItems"?: "true" | "false"; "showItemDescriptions"?: "true" | "false"; "showItemSkus"?: "true" | "false" }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["size"] = all["size"]; delete all["size"];
    query["showSenderPhone"] = all["showSenderPhone"]; delete all["showSenderPhone"];
    query["showRecipientPhone"] = all["showRecipientPhone"]; delete all["showRecipientPhone"];
    query["maskRecipientName"] = all["maskRecipientName"]; delete all["maskRecipientName"];
    query["maskRecipientPhone"] = all["maskRecipientPhone"]; delete all["maskRecipientPhone"];
    query["showShippingCost"] = all["showShippingCost"]; delete all["showShippingCost"];
    query["showInsurance"] = all["showInsurance"]; delete all["showInsurance"];
    query["showItems"] = all["showItems"]; delete all["showItems"];
    query["showItemDescriptions"] = all["showItemDescriptions"]; delete all["showItemDescriptions"];
    query["showItemSkus"] = all["showItemSkus"]; delete all["showItemSkus"];
    return this.call("GET", `/api/v1/shipments/${encodeURIComponent(id)}/label`, query, undefined);
  }

  /** List shipments (GET /api/v1/shipments) */
  shipmentsList(input?: { "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/shipments`, query, undefined);
  }

  /** Rebook a shipment (POST /api/v1/shipments/{id}/rebook) */
  shipmentsRebook(id: string, input?: { "courierCode"?: string; "courierServiceCode"?: string; "courierType"?: string; "price"?: number; "insured"?: boolean; "insurance"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shipments/${encodeURIComponent(id)}/rebook`, query, all);
  }

  /** F-008: live tracking detail (driver, status history, ETA) from Biteship. (GET /api/v1/shipments/{id}/tracking) */
  shipmentsTracking(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/shipments/${encodeURIComponent(id)}/tracking`, {}, undefined);
  }

  /** List areas (GET /api/v1/shipping/areas) */
  shippingAreas(input?: { "q"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["q"] = all["q"]; delete all["q"];
    return this.call("GET", `/api/v1/shipping/areas`, query, undefined);
  }

  /** List config (GET /api/v1/shipping/config) */
  shippingConfig(): Promise<unknown> {
    return this.call("GET", `/api/v1/shipping/config`, {}, undefined);
  }

  /** In Fulkruma we still gate this behind requireAuth: the dashboard always has a session, and we want per-merchant API key resolution. (GET /api/v1/shipping/couriers) */
  shippingCouriers(): Promise<unknown> {
    return this.call("GET", `/api/v1/shipping/couriers`, {}, undefined);
  }

  /** List origin (GET /api/v1/shipping/origin) */
  shippingOrigin(): Promise<unknown> {
    return this.call("GET", `/api/v1/shipping/origin`, {}, undefined);
  }

  /** Create a rate (POST /api/v1/shipping/rates) */
  shippingRates(input: { "destination": Record<string, unknown>; "items": unknown[]; "insurance"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shipping/rates`, query, all);
  }

  /** Set config (PUT /api/v1/shipping/config) */
  shippingSetConfig(input?: { "apiKey"?: string; "defaultOriginId"?: string; "enabledCouriers"?: unknown[]; "defaultCourier"?: string; "active"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PUT", `/api/v1/shipping/config`, query, all);
  }

  /** List shipments (GET /api/v1/shipping/shipments) */
  shippingShipments(input?: { "cursor"?: unknown; "limit"?: unknown; "status"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["limit"] = all["limit"]; delete all["limit"];
    query["status"] = all["status"]; delete all["status"];
    return this.call("GET", `/api/v1/shipping/shipments`, query, undefined);
  }

  /** Get a shipment (GET /api/v1/shipping/shipments/{id}) */
  shippingShipments2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/shipping/shipments/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Legacy namespace. (POST /api/v1/shipping/shipments/{id}/cancel) */
  shippingShipmentsCancel(id: string, input?: { "reason"?: unknown; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shipping/shipments/${encodeURIComponent(id)}/cancel`, query, all);
  }

  /** Legacy shipping namespace. (GET /api/v1/shipping/shipments/{id}/label) */
  shippingShipmentsLabel(id: string, input?: { "size"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["size"] = all["size"]; delete all["size"];
    return this.call("GET", `/api/v1/shipping/shipments/${encodeURIComponent(id)}/label`, query, undefined);
  }

  /** Legacy-namespace twin of /shipments/:id/rebook. (POST /api/v1/shipping/shipments/{id}/rebook) */
  shippingShipmentsRebook(id: string, input?: { "courierCode"?: string; "courierServiceCode"?: string; "courierType"?: string; "price"?: number; "insured"?: boolean; "insurance"?: number; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shipping/shipments/${encodeURIComponent(id)}/rebook`, query, all);
  }

  /** Get a track (GET /api/v1/shipping/track/{waybillId}) */
  shippingTrack(waybillId: string, input?: { "courier"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["courier"] = all["courier"]; delete all["courier"];
    return this.call("GET", `/api/v1/shipping/track/${encodeURIComponent(waybillId)}`, query, undefined);
  }

  /** Update origin (PATCH /api/v1/shipping/origin) */
  shippingUpdateOrigin(input: { "address": string; "province"?: string; "city"?: string; "district"?: string; "village"?: string; "postal"?: string; "areaId"?: string; "lat"?: number; "lng"?: number; "note"?: string; "contactName": string; "contactPhone": string; "couriers"?: unknown[]; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/shipping/origin`, query, all);
  }

  /** Create an adjust (POST /api/v1/shipping-credits/adjust) */
  shippingCreditsAdjust(input: { "amount": number; "kind": "manual_adjustment" | "shipment_refund"; "shipmentId"?: string; "externalRef"?: string; "memo"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shipping-credits/adjust`, query, all);
  }

  /** Create a checkout (POST /api/v1/shipping-credits/checkout) */
  shippingCreditsCheckout(input: { "amount": number; "email"?: string; "name"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shipping-credits/checkout`, query, all);
  }

  /** Balance for the calling merchant. (GET /api/v1/shipping-credits) */
  shippingCreditsList(): Promise<unknown> {
    return this.call("GET", `/api/v1/shipping-credits`, {}, undefined);
  }

  /** Create a topup (POST /api/v1/shipping-credits/topup) */
  shippingCreditsTopup(input: { "amount": number; "externalRef"?: string; "memo"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/shipping-credits/topup`, query, all);
  }

  /** List transactions (GET /api/v1/shipping-credits/transactions) */
  shippingCreditsTransactions(input?: { "limit"?: number; "cursor"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    return this.call("GET", `/api/v1/shipping-credits/transactions`, query, undefined);
  }

  /** Powers the /dashboard overview tiles. (GET /api/v1/stats/overview) */
  statsOverview(): Promise<unknown> {
    return this.call("GET", `/api/v1/stats/overview`, {}, undefined);
  }

  /** Create an adjust (POST /api/v1/stock/adjust) */
  stockAdjust(input: { "variantId": string; "warehouseId": string; "delta": number; "reason": "manual_adjust" | "initial_stock" | "transfer_in" | "transfer_out" | "damaged" | "returned_to_supplier" | "refund_restock" | "import"; "note"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/stock/adjust`, query, all);
  }

  /** List levels (GET /api/v1/stock/levels) */
  stockLevels(input?: { "variant_id"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["variant_id"] = all["variant_id"]; delete all["variant_id"];
    return this.call("GET", `/api/v1/stock/levels`, query, undefined);
  }

  /** List movements (GET /api/v1/stock/movements) */
  stockMovements(input?: { "variant_id"?: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["variant_id"] = all["variant_id"]; delete all["variant_id"];
    return this.call("GET", `/api/v1/stock/movements`, query, undefined);
  }

  /** List reservations (GET /api/v1/stock/reservations) */
  stockReservations(): Promise<unknown> {
    return this.call("GET", `/api/v1/stock/reservations`, {}, undefined);
  }

  /** Create a warehouse (POST /api/v1/warehouses) */
  warehousesCreate(input: { "name": string; "address"?: string; "city"?: string; "postal"?: string; "lat"?: number; "lng"?: number; "phone"?: string; "isDefault"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/warehouses`, query, all);
  }

  /** Delete a warehouse (DELETE /api/v1/warehouses/{id}) */
  warehousesDelete(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/warehouses/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List warehouses (GET /api/v1/warehouses) */
  warehousesList(): Promise<unknown> {
    return this.call("GET", `/api/v1/warehouses`, {}, undefined);
  }

  /** Update a warehouse (PATCH /api/v1/warehouses/{id}) */
  warehousesUpdate(id: string, input?: { "name"?: string; "address"?: string; "city"?: string; "postal"?: string; "lat"?: number; "lng"?: number; "phone"?: string; "isDefault"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/warehouses/${encodeURIComponent(id)}`, query, all);
  }

  /** Register an endpoint. (POST /api/v1/webhooks/endpoints) */
  webhooksCreateEndpoints(input: { "url": string; "events"?: unknown[]; "description"?: string; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("POST", `/api/v1/webhooks/endpoints`, query, all);
  }

  /** Delete an endpoint (DELETE /api/v1/webhooks/endpoints/{id}) */
  webhooksDeleteEndpoints(id: string): Promise<unknown> {
    return this.call("DELETE", `/api/v1/webhooks/endpoints/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** List endpoints (GET /api/v1/webhooks/endpoints) */
  webhooksEndpoints(): Promise<unknown> {
    return this.call("GET", `/api/v1/webhooks/endpoints`, {}, undefined);
  }

  /** List webhook deliveries. (GET /api/v1/webhooks/events) */
  webhooksEvents(input?: { "limit"?: number; "cursor"?: string; "type"?: string; "status"?: "pending" | "sent" | "failed"; "endpointId"?: string }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    query["limit"] = all["limit"]; delete all["limit"];
    query["cursor"] = all["cursor"]; delete all["cursor"];
    query["type"] = all["type"]; delete all["type"];
    query["status"] = all["status"]; delete all["status"];
    query["endpointId"] = all["endpointId"]; delete all["endpointId"];
    return this.call("GET", `/api/v1/webhooks/events`, query, undefined);
  }

  /** Get a webhook delivery. (GET /api/v1/webhooks/events/{id}) */
  webhooksEvents2(id: string): Promise<unknown> {
    return this.call("GET", `/api/v1/webhooks/events/${encodeURIComponent(id)}`, {}, undefined);
  }

  /** Retry a webhook delivery. (POST /api/v1/webhooks/events/{id}/retry) */
  webhooksEventsRetry(id: string): Promise<unknown> {
    return this.call("POST", `/api/v1/webhooks/events/${encodeURIComponent(id)}/retry`, {}, undefined);
  }

  /** Update an endpoint. (PATCH /api/v1/webhooks/endpoints/{id}) */
  webhooksUpdateEndpoints(id: string, input?: { "url"?: string; "events"?: unknown[]; "description"?: string; "active"?: boolean; [field: string]: unknown }): Promise<unknown> {
    const all: Record<string, unknown> = { ...(input ?? {}) };
    const query: Record<string, unknown> = {};
    return this.call("PATCH", `/api/v1/webhooks/endpoints/${encodeURIComponent(id)}`, query, all);
  }
}
